import "./AVContent.css"
;
function AVContent() {
  return(
    <>
    <div className="AVContent_text">
            <h2>Algemene Voorwaarden Mostpros</h2>
            <p>Versie: 1.0 Datum: 28 - 08 - 2023</p>
            <strong> 1. Definities </strong>
            <p>In deze algemene voorwaarden worden een aantal begrippen gehanteerd in enkelvoud en meervoud die met een hoofdletter geschreven zijn en die de betekenis hebben zoals in dit artikel gedefinieerd.</p>

       <p>1.1. Algemene Voorwaarden Mostpros: deze voorwaarden.</p>

       <p>1.2. Algemene Voorwaarden Derden: de door derden gehanteerde leveringsvoorwaarden, licentievoorwaarden, garantievoorwaarden en overige voorwaarden.</p>

       <p>1.3. Mostpros: Mostpros, ingeschreven bij de Kamer van Koophandel onder nr. 67186963 en de ondernemingen die deze Algemene Voorwaarden van toepassing verklaren.</p>

       <p>1.4. Mostpros Producten: alle door Mostpros verstrekte Producten, de daaruit voortvloeiende voorzieningen en daarmee samenhangende werkzaamheden, die afkomstig zijn van Mostpros en waarvan eventuele intellectuele eigendomsrechten en andere rechten bij Mostpros berusten. Mostpros Producten omvatten o.a. door Mostpros ingebrachte standaard technische- en/of design oplossingen en voor algemeen gebruik ontwikkelde en niet-exclusief aan Cliënt beschikbaar gestelde generieke programmatuurelementen, platformen en frameworks van Mostpros.</p>.

       <p> 1.5. Maatwerk: alle door Mostpros verstrekte Producten, specifiek voor Cliënt ontwikkeld (onder diens leiding, toezicht en/of instructies) en schriftelijk aangeduid en overeengekomen als maatwerk waarvan eventuele intellectuele eigendomsrechten en andere rechten bij Cliënt berusten.</p>  1.5. Maatwerk: alle door Mostpros verstrekte Producten, specifiek voor Cliënt ontwikkeld (onder diens leiding, toezicht en/of instructies) en schriftelijk aangeduid en overeengekomen als maatwerk waarvan eventuele intellectuele eigendomsrechten en andere rechten bij Cliënt berusten.

       <p> 1.6. Broncode: de programmeercode die kan worden weergegeven in een formaat, leesbaar en begrijpelijk voor een programmeur. Deze omvat gerelateerde Broncode-documentatie, opmerkingen en procedurele codes. Uit Broncode kan de objectcode worden gecompileerd.
       </p>
       <p>1.7. Cliënt: de partij of persoon die met Mostpros een overeenkomst heeft afgesloten.
       </p>
       <p> 1.8. Derden Producten: alle door Mostpros verstrekte Producten, de daaruit voortvloeiende voorzieningen en de daarmee samenhangende werkzaamheden die afkomstig zijn van derden en waarvan eventuele intellectuele eigendomsrechten, industriële eigendomsrechten en andere rechten in beginsel niet bij Mostpros berusten</p>
       <p> 1.9. Hosting: verstrekking van een niet-exclusieve virtuele Omgeving in een datacenter van een derde waarin voor Cliënt gegevens, programmatuur, Producten (en indien mogelijk apparatuur) kunnen worden geplaatst. Hosting omvat niet de eigen Omgeving van Cliënt (zie art. 3.2 ) en het internet.</p>
       <p> 1.10. Producten: door Mostpros verstrekte producten (inclusief Maatwerk), diensten, voorzieningen en de daarmee samenhangende werkzaamheden in de relatie tussen Mostpros en Cliënt.</p>
       <p> 1.11. Omgeving: de systeemomgeving bestaande uit software, hardware en de randapparatuur waarop een variant van een Product draait, mee communiceert of op enige wijze van afhankelijk is.</p>
       <p> 1.12. Project: een grote Wijziging waarvan Mostpros op basis van ervaring en inzicht inschat dat de definiëring, ontwikkeltijd en uitvoering meer dan 8 uur in beslag neemt.</p>
       <p> 1.13. Responsetijd: de tijd tussen de ontvangst door Mostpros van de melding van de Storing door Cliënt en het moment dat Mostpros streeft te beginnen met het herstel.</p>
       <p> 1.14. SLA: Service Level Agreement, een schriftelijke overeenkomst tussen Mostpros en Cliënt op basis van inspanning waarin afspraken met betrekking tot Producten, zoals Responsetijden en de gewenste kwaliteit kunnen worden afgesproken.</p>
       <p> 1.15. Storing: een fout of gebrek in het Product die het functioneren verstoort die in de functionele beschrijvingen van processen en gegevens in het functioneel ontwerp dan wel technisch ontwerp is vastgelegd. Indien deze beschrijvingen niet beschikbaar zijn, zal er in overleg worden bepaald of het gemelde probleem redelijkerwijs een Storing in het Product betreft. Van een Storing is alleen sprake indien deze kan worden aangetoond en kan worden gereproduceerd. Partijen komen deze definitie overeen, tenzij zij in de overeenkomst hiervan afwijken.</p>
       <p> 1.16. Support: het op verzoek van (gebruikers van) Cliënt of uit eigen initiatief verstrekken van mondelinge en schriftelijke (per e-mail) ondersteuning omtrent de technische- en ontwikkelaspecten van de Producten en daarmee samenhangende elementen. Cliënt is verantwoordelijk en zorgt voor eerstelijns- support, zijnde het registreren en aanmelden van Storingen aan Mostpros en het versteken van ondersteuning aan gebruikers voor wat betreft de functionele aspecten van de Producten.</p>
       <p> 1.17. Uitwijkprocedure: een uitgewerkt beleid en middelen waarover Cliënt beschikt om in het geval van Storingen het verstoorde bedrijfsproces op alternatieve wijze kan continueren.</p>
       <p>  1.18. Werkdagen: normale Nederlandse werktijden ( 9.00 - 17.00 CET) op maandag t/m vrijdag, uitgezonderd nationale en in Nederland erkende feestdagen.</p>

       <p> 1.19. Wijziging: een aanpassing in de Broncode die effect heeft op de functionaliteit, technische werking of de beschikbaarheid van een Product.</p>

       <p>1.20. Software as a Service: dienst bestaande uit het ter beschikking stellen van functionaliteit op afstand via elektronische weg.</p>
        <strong>2. Aanbiedingen en overeenkomsten
        </strong>
       <p>2.1. Deze Algemene Voorwaarden zijn van toepassing op alle aanbiedingen, rechtsbetrekkingen en overeenkomsten waarbij Mostpros Producten aan Cliënt levert. Toepasselijkheid van inkoop- of andere voorwaarden van Cliënt wordt uitdrukkelijk van de hand gewezen.</p>
       <p>2.2. Deze Algemene Voorwaarden vervangen alle voorgaande voorwaarden alsmede de door Mostpros eerder gedane toezeggingen. Van deze voorwaarden kan uitsluitend schriftelijk worden afgeweken door een bevoegd vertegenwoordiger van Mostpros.
       </p>
       <p>2.3. Alle aanbiedingen en uitingen van Mostpros zijn vrijblijvend, tenzij door Mostpros schriftelijk uitdrukkelijk anders is aangegeven. Cliënt staat in voor de juistheid en volledigheid van de door of namens hem aan Mostpros opgegeven specificaties en andere gegevens waarop Mostpros zijn aanbieding baseert.
       </p>
       <p>2.4. Tenzij uit de aanbieding anders blijkt, zijn aanbiedingen herroepbaar en een maand geldig. Prijsopgaven en aanbiedingen kunnen wijzigingen ondergaan door een onvoorziene verandering in de werkzaamheden, specificaties of situatie. Cliënt kan aan zetfouten en verschrijvingen geen rechten ontlenen; Mostpros zal dergelijke onvolkomenheden onverwijld aan Cliënt melden zodra Mostpros deze bemerkt.
       </p>
       <strong>3. Randvoorwaarden</strong>
       <p>3.1. Voor een succesvol project, Producten of samenwerking zijn een compleet beeld van de situatie en goede communicatie essentiële voorwaarden. Cliënt staat er daarom voor in als goed opdrachtgever tijdig aan Mostpros alle volgens Mostpros nuttige en nodige gegevens te verstrekken en alle (on-)gevraagde medewerking te verlenen. Wanneer Cliënt personeel, of derden ter beschikking stelt voor een Product, zorgt Cliënt altijd ervoor dat zij ter zake kundig zijn en beschikken over de vereiste kennis, middelen en bevoegdheden. Tenzij uitdrukkelijk anders aangegeven, gaat Mostpros ervan uit dat Cliënt steeds een goed voorbereidde professionele partij is die zorgvuldig handelt en anticipeert op (mogelijke) problemen en met Mostpros werkt richting het gezamenlijke doel. Cliënt is te allen tijde verantwoordelijk voor de juistheid en volledigheid van functionele specificaties en aangeleverde gegevens, ook indien de functionele specificaties in opdracht van Cliënt door Mostpros zijn opgesteld.</p>
       <p>3.2. Cliënt is verantwoordelijk voor zijn eigen Omgeving, waarin Producten van Mostpros geleverd worden of functioneren. Cliënt erkent dat de Omgeving van wezenlijk belang is voor de goede werking van zijn bedrijfsprocessen, Producten en daaruit voortvloeiende voorzieningen en zorgt daarom zelf voor de selectie, toepassing, beschikking over de benodigde rechten en producten, het beheer van zijn Omgeving, gegevens, bestanden en andere door Mostpros aan te wijzen randvoorwaarden voor Producten. Indien Cliënt dat wenst kan Mostpros inlichtingen verschaffen over de randvoorwaarden voor diens Omgeving voor installatie, implementatie en ingebruikneming van de Producten en voor de juiste instellingen van de apparatuur, programmatuur, websites, gegevens, bestanden en andere producten en materialen.
       </p>
       <p>3.3. Mostpros heeft zijn personeel geïnstrueerd om alle redelijke voorschriften en normen van Cliënt te respecteren. Als Cliënt wil dat personeel van Mostpros dergelijke normen naleeft, dient Cliënt alle geldende huisregels en voorschriften vóór aanvang van de werkzaamheden aan het betrokken personeel van Mostpros kenbaar te maken. Vooraf en gedurende levering draagt Cliënt kosteloos zorg voor de door Mostpros in redelijkheid gewenste faciliteiten, zoals een veilige werkruimte met computer-, data- en telecommunicatiefaciliteiten die voldoen aan de wettelijke en gebruikelijke (arbeids-)normen.
       </p>
       <p>3.4. Indien en zolang Cliënt de in dit artikel omschreven en/of overeengekomen gegevens, voorwaarden, personen, partijen die nodig zijn de voor de uitvoering van de overeenkomst niet, te laat of op andere wijze aanlevert, of de Omgeving niet voldoet aan de door Mostpros gestelde randvoorwaarden, of indien cliënt op andere wijze niet aan zijn verplichtingen voldoet, kan Mostpros niet op enige wijze gehouden worden aan diens verplichtingen die daarmee (in-)direct verband houden, onverminderd het recht om de daardoor ontstane kosten volgens zijn dan geldende tarieven in rekening te brengen. Schade die ontstaat door ondeskundigheid, onzorgvuldig handelen of handelen strijd met de instructies van Mostpros blijven voor rekening van Cliënt, tenzij er sprake is van opzettelijk handelen door personeel van Mostpros.
       </p>
       <strong>4. Leveringstermijnen
       </strong>
       <p>4.1. Alle door Mostpros genoemde of overeengekomen (leverings)termijnen zijn naar beste weten vastgesteld op grond van de gegevens die bij het aangaan van de overeenkomst bij Mostpros bekend waren. Mostpros spant zich er voor in overeengekomen (leverings)termijnen zoveel mogelijk in acht te nemen. Termijnen zijn alleen fataal indien Mostpros deze inclusief de gevolgen van overschrijding uitdrukkelijk schriftelijk overeenkomt. De enkele overschrijding van een genoemde of overeengekomen (leverings)termijn brengt Mostpros niet in verzuim. Cliënt kan geen aanspraak maken op mogelijke ontstane schade door de enkele overschrijding van een genoemde of overeengekomen (leverings)termijn.
       </p>
       <p>4.2. Mostpros geraakt in verzuim nadat Cliënt Mostpros, onverwijld en deugdelijk, schriftelijk in gebreke stelt, daarbij stellende een redelijke termijn ter zuivering van de tekortkoming of Storing en Mostpros ook na die termijn toerekenbaar in de nakoming van zijn verplichtingen tekort blijft schieten. De ingebrekestelling dient een zo gedetailleerd mogelijke omschrijving van de tekortkoming of Storing te bevatten, zodat Mostpros in staat is om adequaat te reageren.
       </p>
       <p>4.3. Mostpros is niet gebonden aan (leverings)termijnen die vanwege buiten zijn macht gelegen omstandigheden niet meer gehaald kunnen worden. Evenmin is Mostpros gebonden aan overeengekomen (leverings)termijn indien de gegevens die bij het aangaan van de overeenkomst aan Mostpros bekend waren wijzigen, de inhoud of omvang van de overeenkomst verandert (meerwerk, wijziging van specificaties enz.) of partijen anders overeenkomen. Partijen komen in voornoemde gevallen samen nieuwe termijnen overeen.
       </p>
       <p>4.4. Indien overschrijding van enige termijn dreigt, zullen Mostpros en Cliënt zo spoedig mogelijk in overleg treden om te komen tot een passende oplossing.
       </p>
       <strong>5. Flexibele aard van de dienstverlening</strong>
       <p>5.1. Mostpros streeft er naar om Cliënt optimaal te laten genieten van de overeengekomen Producten gelet de omstandigheden. De behoeften van Cliënt, Mostpros en de wereld waarin partijen opereren zijn niet statisch. Mostpros staat open voor verzoeken van Cliënt tot wijziging van Producten en zal aangeven wat nodig is om aan deze verzoeken te kunnen voldoen. Cliënt verleent Mostpros bij voorbaat toestemming om haar Producten gedurende levering aan te passen in reactie op veranderingen in de stand van techniek, bedrijfsvoering van Mostpros en de wetgeving.
       </p>
       <p>5.2. Mostpros mag aanpassingen in de Producten aanbrengen voor wat betreft doch niet beperkt tot: het wijzigen van elementen, personen en toeleveranciers om de overeengekomen Producten te leveren, procedures voor levering, functionaliteit, beveiligingseisen en maatregelen die voortvloeien uit wettelijke verplichtingen. Daarbij neemt Mostpros de kwaliteit van de dienstverlening aan Cliënt altijd mee en probeert hinder te voorkomen, terwijl Cliënt een coöperatieve houding aanneemt en aanpassingen niet zal weigeren, tenzij Cliënt aantoont dat de functionaliteit en kwaliteit van de Producten wezenlijk is verslechterd (of zal verslechteren) door de aanpassing.</p> 
       <p>5.3. Aanpassen van Producten doet Mostpros bij voorkeur in overleg. Op grond van veranderingen mag Mostpros enerzijds Cliënt onverplicht informeren over technologische ontwikkelingen en mogelijkheden voor Producten. Cliënt zal anderzijds Mostpros voortdurend op de hoogte houden van haar (veranderende) behoeften en de diensten die zij ten behoeve van haar eigen communicatie- en informatiesystemen wenst te gaan implementeren, of daarmee op enige wijze te verbinden.</p>
       <strong>6. Uitvoering van de overeenkomst</strong>
       <p>6.1. Mostpros zal zich naar beste kunnen inspannen de Producten te leveren of verlenen overeenkomstig de met Cliënt schriftelijk vastgelegde afspraken en procedures. Specifieke afspraken m.b.t. Producten, zoals een SLA, worden enkel schriftelijk overeengekomen. Mostpros is niet gehouden tot afspraken, of levering van of eisen aan Producten die niet zijn overeengekomen.</p>    
       <p>6.2. Indien Mostpros op verzoek of met voorafgaande instemming van Cliënt werkzaamheden of andere prestaties heeft verricht die buiten de inhoud of omvang van de overeenkomst vallen, zullen deze werkzaamheden of prestaties door Cliënt worden vergoed volgens de gebruikelijke tarieven van Mostpros. Van meerwerk is eveneens sprake indien een ontwerp of specificaties worden uitgebreid of gewijzigd. Mostpros is nimmer verplicht aan een dergelijk verzoek te voldoen en kan steeds verlangen dat daarvoor afzonderlijke schriftelijke overeenkomst wordt gesloten.</p>
       <p>6.3. Indien Mostpros gegevens over Producten op enige wijze deelt met Cliënt, zoals rapportages over geleverde diensten, technische analyses, berichten in kader van beheer, logs enz. dan worden deze geacht correct te zijn, tenzij Cliënt binnen bekwame periode bezwaar maakt, voorzien van objectief bewijs waaruit het tegendeel blijkt.</p>
       <p>6.4. Indien Mostpros bij Producten licentiesleutels, accounts, wachtwoorden e.d. verstrekt is Cliënt verplicht deze met zorg in diens organisatie te plaatsen en alle technische en organisatorische maatregelen te treffen om te voorkomen dat deze gegevens gedeeld worden met derden of dat derden toegang kunnen verschaffen tot gegevens van Cliënt of Producten van Mostpros, of deze toepassen voor onoorbare of inbreukmakende activiteiten. Cliënt vrijwaart Mostpros voor alle gevolgen van toegang en gebruik van gegevens en Producten door onbevoegden. Indien Cliënt vermoedt dat toegang of gebruik van (onderdelen van) Producten op ongewenste wijze plaatsvindt is zij verplicht dit direct aan Mostpros te melden en ook zelf de nodige maatregelen te nemen om misbruik van de Omgeving te voorkomen en te beperken.</p>    
       <strong>7. Aflevering en acceptatie</strong>
       <p>7.1. Levering van Producten geschiedt behoudens afwijkende schriftelijke afspraken tijdens Werkdagen op een door Mostpros bekend te maken locatie en wijze. Aflevering van Producten geschiedt af bedrijf Mostpros. Het risico van het Product gaat over op Opdrachtgever bij levering. Indien er sprake is van transport, verzending of indien Cliënt de wijze van transport wenst te bepalen is Cliënt hiervoor verantwoordelijk en komen eventuele kosten en verzekeringen voor rekening van Cliënt.</p>
       <p>7.2. Mostpros zal de Producten aan Cliënt conform de schriftelijk overeengekomen specificaties leveren en/of uitvoeren. In overleg kunnen partijen schriftelijk overeenkomen dat Mostpros onder door Mostpros te stellen voorwaarden de Producten installeert, bij gebreke waarvan Mostpros niet gehouden is om tot installatie over te gaan.</p>
       <p>7.3. Indien Producten bestaan uit diensten, geschiedt acceptatie direct na uitvoering van de diensten.</p> 
       <p>7.4. Uitsluitend in het geval waar installatie door Mostpros plaatsvindt en de Producten nog niet door Cliënt zijn geaccepteerd zal er onmiddellijk na voltooiing van de installatie een acceptatieperiode van toepassing zijn. Deze acceptatieperiode voor Cliënt bedraagt tien Werkdagen. Gedurende de acceptatieperiode is het Cliënt niet toegestaan de Producten voor productieve of operationele doeleinden te gebruiken. Indien de installatie op een productie-Omgeving gebeurt en de Producten reeds zijn geaccepteerd dan is voorgaande niet van toepassing.</p>   
       <p>7.5. De Producten zullen tussen partijen gelden als geaccepteerd:</p>
       <ol>
          <li dir="ltr"><p dir="ltr">bij de aflevering indien er geen acceptatieperiode van toepassing is; dan wel</p></li>
          <li dir="ltr"><p dir="ltr">indien er een acceptatieperiode van toepassing is: op de eerste dag na de acceptatieperiode; dan wel</p></li>
          <li dir="ltr"><p dir="ltr">indien Mostpros een positief testrapport of melding ontvangt van acceptatie of bericht waaruit acceptatie op enige wijze volgt. Indien gedurende de acceptatieperiode blijkt dat Producten fouten of Storingen bevatten die de (voortgang van de) acceptatie belemmeren, zal Cliënt Mostpros binnen de acceptatieperiode over deze fouten of Storingen informeren door middel van een schriftelijk, gedetailleerd testrapport, in welk geval de nog resterende acceptatieperiode onderbroken wordt totdat het Product zodanig is aangepast dat de fouten zijn verholpen.</p></li>
       </ol>
       <p>7.6. Acceptatie van de Producten mag niet worden onthouden op andere gronden dan die, welke verband houden met de tussen partijen uitdrukkelijk overeengekomen specificaties en voorts niet wegens het bestaan van kleine fouten die operationele of productieve ingebruikname van de Producten redelijkerwijs niet in de weg staan.</p>    
       <p>7.7. Indien de Producten in fasen of onderdelen worden geleverd of getest, laat de niet-acceptatie van een bepaalde fase of onderdeel een eventuele acceptatie van een eerdere fase of een ander onderdeel onverlet. Indien is overeengekomen dat de dienstverlening in fasen zal plaatsvinden, is Mostpros voorts gerechtigd de aanvang van de werkzaamheden die tot een fase behoren uit te stellen totdat Cliënt de resultaten van de daaraan voorafgaande fase schriftelijk heeft goedgekeurd.</p>
       <p>7.8. In afwijking van het voorgaande zullen de Producten, indien Cliënt daarvan voor het moment van acceptatie enig gebruik voor productieve of operationele doeleinden maakt, of door betaling van de gerelateerde factuur, reeds gelden als volledig geaccepteerd vanaf de aanvang van dat gebruik.</p>
       <strong>8. Hosting</strong>
       <p>8.1. De Hosting wordt op de overeengekomen (of bij gebreke daarvan op de door Mostpros bepaalde) wijze aangesloten op het publieke internet, waarna toegang mogelijk is. Voor toegang zorgt (de gebruiker van) Cliënt zelf voor de nodige voorzieningen zoals een internetverbinding, apparatuur en software om de Omgeving en daarin aanwezige gegevens te kunnen gebruiken.</p>
       <p>8.2. Bij Hosting verkrijgt Cliënt het tijdelijke, beperkte recht de gehoste Omgeving te gebruiken voor legitieme doeleinden. Bij ieder gebruik zal Cliënt de overeenkomsten met Mostpros, Algemene Voorwaarden Derden (de voorwaarden van het datacenter en Derden Producten) aanwijzingen van Mostpros naleven, welke geacht worden deel uit te maken van de overeenkomst inzake Hosting tussen Cliënt en Mostpros. Voorts zal Cliënt de gehoste Omgeving steeds op redelijke wijze (ook wel ‘fair-use’) gebruiken. Het is verboden de Omgeving te verhuren of te bezwaren met beperkte rechten.</p>
       <p>8.3. Hosting bestaat uitsluitend uit de expliciet overeengekomen diensten. Indien partijen dit schriftelijk overeenkomen kan Mostpros de Hosting uitbreiden met andere Producten op basis van nacalculatie, zoals Support of het installeren van updates van Producten voor de Omgeving. Cliënt draagt de verantwoordelijkheid voor beheer, verwerking en beveiliging van de gegevens die zich in de gehoste Omgeving bevinden. Daarnaast is Cliënt verantwoordelijk voor eventuele software (niet zijnde Mostpros Producten) en/of apparatuur die Cliënt in de Omgeving plaatst.</p>
       <p>8.4. Bij Hosting dient een Storing zich te bevinden binnen de gehoste Omgeving.</p>
       <strong>9. Gegevens van Cliënt</strong>
       <p>9.1. Cliënt is eigenaar van haar eigen informatie en (persoons-)gegevens (verder: gegevens) en draagt aldus zelf verantwoordelijkheid voor de bescherming van gegevens die worden verzonden, bewerkt, of opgeslagen door Producten van Mostpros. Mostpros is geen verwerker noch verantwoordelijke van Cliënt’s gegevens in de zin de Wet bescherming persoonsgegevens. Mostpros levert Producten en kan helpen deze in te stellen, zodat Cliënt in staat is zijn gegevens te maken, bewerken en opslaan.</p>
       <p>9.2. Voor zover Mostpros in het kader van de uitvoering van een overeenkomst persoonsgegevens ten behoeve van Cliënt wel zou verwerken, wordt Mostpros uitsluitend voor die bewerkingen als ‘verwerker’ en Cliënt ‘verantwoordelijke’ in de zin van de Wet Bescherming Persoonsgegevens (WBP) aangemerkt. In dat geval zullen deze Voorwaarden tevens gelden als een verwerkersovereenkomst in de zin van de WBP. De verantwoordelijkheid voor naleving van de toepasselijke verplichtingen van de WBP, zoals de informatieplicht, inzage-, en correctierechten enz. inzake persoonsgegevens blijven steeds geheel en alleen bij de verantwoordelijke. Cliënt staat er voor in en zorgt dat zij steeds beschikt over de vereiste toestemming van betrokkenen voor alle bewerkingen op persoonsgegevens die Mostpros uitvoert als bewerker.</p>
       <p>9.3. Met uitzondering van hetgeen in het eerste lid is gesteld, blijft Mostpros verantwoordelijk voor de bescherming van persoonsgegevens zoals bepaald in 9. 2 waarvan het gebruik door Mostpros noodzakelijk is voor het correct uitvoeren van de overeenkomst en zij zal Cliënt vrijwaren van aansprakelijkheid in het geval dat Cliënt in rechte wordt aangesproken door een natuurlijk persoon op grond van een inbreuk op de persoonlijke levenssfeer als gevolg van een handelen of nalaten van Mostpros met inachtneming van artikel 11. Cliënt vrijwaart Mostpros van alle claims wegens inbreuk op de persoonlijke levenssfeer die op enige wijze in verband staan met de gegevens en producten die Cliënt levert.</p>
       <p>9.4. Cliënt is zich bewust dat regelgeving op gebied van persoonsgegevens kan veranderen in de toekomst of dat de aard van de dienstverlening kan nopen tot extra maatregelen en informeert zichzelf hierover. Indien noodzakelijk treden partijen in overleg om passende afspraken te maken over de toepasselijke rechten en verplichtingen die uit (toekomstige) wetgeving kunnen voortvloeien.</p>
       <p>9.5. Voor zover Cliënt daartoe gerechtigd is en voorzover nodig in het kader van de overeenkomst, stemt Cliënt uitdrukkelijk in met het opnemen van (persoons- )gegevens van gebruikers in de persoonsregistratie van Mostpros voor doeleinden van administratie en beheer. Deze persoonsregistratie bevat onder meer identificatiegegevens en gegevens voor uitvoering van de overeenkomst en is slechts toegankelijk voor Mostpros. Deze gegevens worden niet aan derden verstrekt, behoudens toestemming van Cliënt of in de gevallen wanneer Mostpros hier krachtens de wet of een rechterlijke uitspraak toe verplicht is.</p>
       <p>9.6. Mostpros is steeds gerechtigd de naam en het logo van Cliënt en het project waaraan Mostpros Producten levert en/of heeft geleverd op haar website te plaatsen, te gebruiken als referentie en deze aan derden ter informatie beschikbaar te stellen. Partijen kunnen schriftelijk nadere afspraken overeenkomen ten aanzien van de omgang met project-specifieke gegevens die Cliënt aanwijst als vertrouwelijk.</p>
       <strong>10. Back-up</strong>
       <p>10.1. Omdat geen enkele Omgeving onfeilbaar is, dient Cliënt zelf te bepalen welke gegevens in aanmerking dienen te komen voor back-up en de nodige voorzieningen te treffen om gegevensverlies en afhankelijkheden te minimaliseren. Daarom staat Cliënt in voor de verzorging van een Uitwijkprocedure die wordt nageleefd door haar medewerkers en deze periodiek te herzien.</p>
       <p>10.2. Partijen kunnen overeenkomen dat Mostpros back-ups maakt, in welk geval Mostpros de door Cliënt in een bepaalde Omgeving aangewezen gegevens zal instellen om te laten kopiëren en opslaan. Mostpros is in geen enkel geval aansprakelijk voor deze back-ups voor wat betreft doch niet beperkt tot Storingen in de back-up waaronder het geheel dan wel deels onbruikbaar zijn of verloren gaan van een back-up. Cliënt blijft ten alle tijden zelf verantwoordelijk voor de gegevens en informatie die zij verzamelt, wijzigt en beheert en verwijdert.</p>
       <p>10.3. Cliënt test geregeld in overleg met Mostpros of de back-up de beoogde gegevens bevat, aangezien Mostpros dit niet kan bepalen voor Cliënt. Mostpros zal op verzoek van Cliënt tegen vergoeding assisteren bij het uitvoeren van deze controles.</p>
       <strong>11. Aansprakelijkheid</strong>
       <p>11.1. De totale aansprakelijkheid van Mostpros zal, met inachtneming van voorwaarden in de leden van dit artikel, beperkt blijven tot vergoeding van directe schade en dan tot ten hoogste de factuurwaarde van het gedeelte van de overeenkomst, waaruit die aansprakelijkheid voortvloeit (exclusief BTW) met een maximum van € 250.000,- (tweehonderdvijftigduizend euro), waarbij een reeks van samenhangende gebeurtenissen geldt als één gebeurtenis.</p>
       <p>11.2. Indien de overeenkomst tevens uit een duurovereenkomst bestaat, met een looptijd van meer dan 1 (één) jaar en de aansprakelijkheid van Mostpros vloeit voort uit deze duurovereenkomst, wordt de bedongen prijs gesteld op ten hoogste het totaal van de vergoedingen (exclusief BTW) daadwerkelijk betaald door Cliënt aan Mostpros op basis van de duurovereenkomst voor 1 (één) jaar (zijnde het jaar waarin de schade zich heeft voorgedaan) met een maximum van € 250.000,- (tweehonderdvijftigduizend euro).</p>
       <p>11.3. Mostpros heeft zich ter zake van schade verzekerd. Mostpros is in ieder geval niet aansprakelijk voor verdere schade en zal deze verdere schade ook niet vergoeden, die Cliënt uit hoofde van de met Mostpros gesloten overeenkomst, hoe en uit welke hoofde dan ook ontstaan, zulks met inbegrip van mogelijke aanspraken op Cliënt van derden, mocht lijden, dan door deze verzekering gedekt wordt en daadwerkelijk vergoed vermeerderd met Mostpros’s eigen risico, tenzij er sprake is van opzet of bewuste roekeloosheid.</p>
       <p>11.4. De totale aansprakelijkheid van Mostpros voor schade door dood of lichamelijk letsel zal in geen geval meer bedragen dan € 1.000.000,- (één miljoen euro), waarbij een reeks van samenhangende gebeurtenissen geldt als één gebeurtenis.</p>
       <p>11.5. Onder directe schade wordt uitsluitend verstaan:</p>
       <p>11.5.1. De redelijke kosten, gemaakt ter vaststelling van de oorzaak en de omvang van de schade;</p>
       <p>11.5.2. De redelijke kosten, gemaakt ter voorkoming of beperking van schade, voor zover Cliënt aantoont dat deze kosten hebben geleid tot beperking van schade.</p>
       <p>11.6. Aansprakelijkheid van Mostpros voor indirecte schade, daaronder begrepen gevolgschade, gederfde winst, gemiste besparingen, vernietiging of zoekraken van bestanden en/of gegevens, vertragingsschade, geleden verlies, schade veroorzaakt door het gebrekkig verschaffen van informatie en/of verlening van medewerking door Cliënt, schade door bedrijfsstagnatie of vorderingen van derden op Cliënt, is nadrukkelijk uitgesloten.</p>
       <p>11.7. Buiten het in dit artikel genoemde gevallen rust op Mostpros geen enkele aansprakelijkheid voor schadevergoeding, ongeacht de grond waarop een actie tot schadevergoeding zou worden gebaseerd.</p>
       <p>11.8. Cliënt vrijwaart Mostpros van alle aanspraken van derden wegens aansprakelijkheid als gevolg van een gebrek in een product, systeem dan wel dienst door Cliënt aan een derde (af)geleverd en welk product, systeem dan wel dienst mede bestond uit hetgeen door Mostpros is afgeleverd.</p>
       <p>11.9. Mostpros aanvaardt geen enkele aansprakelijkheid voor schade van welke aard dan ook, ontstaan door Derden Producten, die Mostpros aan Cliënt heeft afgeleverd. Indien mogelijk zal Mostpros zijn rechten tot het vorderen van schadevergoeding bij de leverancier van het Derden Product in kwestie overdragen aan Cliënt.</p>
       <p>11.10. Mostpros is niet aansprakelijk voor schade van welke aard dan ook die het gevolg is van het niet-tijdig verstrekken van support, onderhoud en garantie, tenzij Cliënt daartoe de benodigde Producten heeft afgenomen en voldaan aan al zijn verplichtingen, waaronder maar niet beperkt tot volledige betaling.</p>
       <strong>12. Betaling en prijs</strong>
       <p>12.1. Alle door Mostpros uit de overeenkomst met Cliënt voortvloeiende kosten komen voor rekening van Cliënt. Cliënt dient de door Mostpros uitgeschreven factuur via overmaking van het totaalbedrag te voldoen, zonder tot enige aftrek of verrekening gerechtigd te zijn. Het betalen van facturen dient ten hoogste 30 dagen na het uitschrijven van de rekening te geschieden, tenzij schriftelijk anders is overeengekomen. Betaling is een fundamentele kernverplichting van Cliënt.</p>
       <p>12.2. Door Cliënt gedane betalingen strekken steeds ter afdoening van ten eerste de verschuldigde rente en kosten, en ten tweede van opeisbare facturen die het langst open staan, zelfs al vermeldt de wederpartij, dat de voldoening betrekking heeft op een latere factuur of verbintenis.</p>
       <p>12.3. Indien Mostpros geen betaling heeft ontvangen na ommekomst van voornoemde betalingstermijn is Cliënt, zonder dat hiervoor een ingebrekestelling vereist is, in verzuim. Mostpros zal Cliënt hier van op de hoogte stellen en Cliënt de mogelijkheid geven om binnen een termijn van 14 dagen alsnog aan zijn betalingsverplichting te voldoen. Indien betaling uitblijft is Cliënt over het openstaande factuurbedrag de wettelijke rente verschuldigd, verhoogd met 1,5%, per maand, waarbij een gedeelte van een maand als een hele maand geldt. Verder is Mostpros bij deze gerechtigd het door de klant verschuldigde bedrag te verhogen met alle gemaakte (buiten) gerechtelijke invorderingskosten en uitgaven, waaronder mede begrepen kosten van advocaten, deurwaarders, interne kosten etc. Worden deze kosten niet tijdig voldaan, dan zullen die, vooruitlopend op de vaststelling van de werkelijke kosten, voorlopig worden bepaald op een direct opeisbaar bedrag van 15% van de onbetaalde factuur, met een minimum van € 250,00.</p>
       <p>12.4. Mostpros heeft het recht zijn dienstverlening en overige verplichtingen op te schorten, totdat algehele betaling heeft plaatsgevonden, onverminderd de gehoudenheid van Cliënt om aan zijn verplichtingen te voldoen. Aan (de gevolgen van) opschorting kan Cliënt geen aanspraken of recht op compensatie jegens Mostpros ontlenen.</p>
       <p>12.5. Indien Cliënt in enig opzicht niet voldoet aan zijn verplichtingen jegens Mostpros, is hetgeen hij uit de hoofde van die verplichting verschuldigd is onmiddellijk opeisbaar. Mostpros is in het geval van ingebrekestelling gerechtigd naar haar keuze alle in het kader van die relatie gestelde zekerheden of gedeelten daarvan te realiseren, ten einde uit de opbrengst te verhalen hetgeen aan Mostpros volgens haar administratie verschuldigd is, inclusief de wettelijke rente en de door Mostpros te specificeren kosten.</p>
       <p>12.6. Alle prijzen zijn, tenzij anders vermeld, exclusief omzetbelasting (BTW) en andere heffingen welke van overheidswege worden opgelegd.</p>
       <p>12.7. Indien sprake is van een periodieke betalingsverplichting van Cliënt, geldt dat Mostpros gerechtigd is schriftelijk op een termijn van ten minste drie maanden de geldende prijzen en tarieven aan te passen. Indien Cliënt niet akkoord wenst te gaan met een dergelijke aanpassing, is Cliënt gerechtigd binnen dertig dagen na kennisgeving de overeenkomst te beëindigen tegen de datum waarop de aanpassing daadwerkelijk in werking is getreden.</p>
       <strong>12.7. Indien sprake is van een periodieke betalingsverplichting van Cliënt, geldt dat Mostpros gerechtigd is schriftelijk op een termijn van ten minste drie maanden de geldende prijzen en tarieven aan te passen. Indien Cliënt niet akkoord wenst te gaan met een dergelijke aanpassing, is Cliënt gerechtigd binnen dertig dagen na kennisgeving de overeenkomst te beëindigen tegen de datum waarop de aanpassing daadwerkelijk in werking is getreden.</strong>
       <p>13.1. Mostpros behoudt zich de eigendom van alle door haar geleverde Producten tot op het moment van volledige betaling van de (periodieke) vergoedingen van alle door Mostpros aan Cliënt geleverde of nog te leveren Producten, alsmede van eventuele vorderingen voor door Mostpros ten behoeve van Cliënt in het kader van de levering van goederen verrichtten of nog te verrichten werkzaamheden en of diensten en hetgeen Mostpros van de klant te vorderen mocht hebben wegens een tekortkoming van Cliënt in de nakoming van de tussen Mostpros en Cliënt gesloten overeenkomst, daaronder begrepen incassokosten, rente en boeten.</p>
       <strong>14. Derden Producten</strong>
       <p>14.1. Mostpros is gerechtigd Derden Producten te verstrekken dan wel Derden Producten te betrekken bij het vervullen van zijn verplichtingen voortvloeiende uit de overeenkomst. Mostpros is niet verantwoordelijk voor Derden Producten, tenzij schriftelijk anders overeengekomen. Een voorbeeld van Derden Producten zijn open source producten.</p>
       <p>14.2. Indien Mostpros Derden Producten levert aan Cliënt, dan zijn naast onderhavige voorwaarden tevens de Algemene Voorwaarden Derden van toepassing op de overeenkomst. Mostpros levert rechten op Derden Producten onder de voorwaarden als omschreven in de Algemene Voorwaarden Derden. Algemene Voorwaarden Derden die in deze Algemene Voorwaarden Mostpros van toepassing worden verklaard, zullen, indien beschikbaar bij Mostpros, op verzoek worden toegezonden. De Algemene Voorwaarden Derden zullen in hetzelfde formaat en dezelfde taal ter beschikking worden gesteld zoals Mostpros deze heeft ontvangen.</p>
       <p>14.3. De Algemene Voorwaarden Mostpros treden in rangorde boven de Algemene Voorwaarden Derden tenzij anders aangegeven. Bij strijd tussen de Algemene Voorwaarden Mostpros en de Algemene Voorwaarden Derden, kan Mostpros de desbetreffende strijdige bepalingen in de Algemene Voorwaarden Derden buiten toepassing verklaren dan wel voorrang verlenen boven Algemene Voorwaarden Mostpros.</p>
       <p>14.4. Er vindt door Mostpros geen Onderhoud, Support dan wel andere diensten plaats met betrekking tot Derden Producten, tenzij schriftelijk anders overeengekomen.</p>
       <p>14.5. Met betrekking tot geleverde Derden Producten verzorgt Mostpros:</p>
       <p>14.5.1. De service op Derden Producten, onder maximaal dezelfde voorwaarden die worden weergegeven in de Algemene Voorwaarden Derden.</p>
       <p>14.5.2. De garantie voor de termijn en onder maximaal dezelfde voorwaarden als weergegeven in de Algemene Voorwaarden Derden.</p>
       <p>14.6. Onder geen beding zal vervanging van afgeleverde Derden Producten plaatsvinden, tenzij Cliënt dit uitdrukkelijk verzoekt en de daaraan verbonden kosten voldoet, zoals bijvoorbeeld overeengekomen in een Supportovereenkomst. Aan alle reparaties zijn behandelingskosten verbonden. Indien reparaties elders geschieden dan bij Mostpros worden er tevens voorrijkosten, uurlonen en andere daaraan verbonden kosten in rekening gebracht.</p> 
       <strong>15. Intellectueel eigendom</strong>
       <p>15.1. Tenzij er sprake is van Derden Producten of Maatwerk, komen alle uit de levering van Producten en programmatuur voortkomende rechten van intellectueel en industrieel eigendom toe aan Mostpros, ongeacht of er sprake is van de aflevering van een bestaand Product dan wel een nog te ontwikkelen Product. Voor zover een dergelijk recht slechts verkregen kan worden door een depot of registratie, dan is uitsluitend Mostpros daartoe bevoegd.</p>
       <p>15.2. Indien er sprake is van Maatwerk komen alle uit een door Mostpros uitgevoerde opdracht voortvloeiende intellectuele eigendomsrechten, industriële eigendomsrechten en andere rechten met betrekking tot het Maatwerk (waaronder de Broncode en objectcode) toe aan Cliënt. De rechten op de Mostpros Producten, alsook programmatuur van derden waarvan de rechten niet bij Mostpros rusten (Derden producten), komen niet toe aan Cliënt.</p>
       <p>15.3. Cliënt heeft het exclusieve recht het Maatwerk zelfstandig verder te ontwikkelen en het gebruik daarvan middels licenties aan derden ter beschikking te stellen. Mostpros heeft het exclusieve recht de Mostpros Producten verder te ontwikkelen en het gebruik daarvan middels licenties aan derden ter beschikking te stellen, tenzij het gaat om Maatwerk in welk geval Mostpros slechts, na voorafgaande schriftelijke goedkeuring van Cliënt, het recht heeft het Maatwerk verder te ontwikkelen en het gebruik daarvan middels licenties aan derden ter beschikking te stellen. Indien het Maatwerk van Cliënt Mostpros Producten bevat, heeft Cliënt het niet-exclusieve en niet-herroepbare recht de bij haar in gebruik zijnde Mostpros Producten zelfstandig verder te ontwikkelen en het gebruik daarvan middels licenties aan derden ter beschikking te stellen, mits de Mostpros Producten alleen onderdeel blijven uitmaken van het Maatwerk van Cliënt.</p>
       <p>15.4. Als Mostpros intellectuele of industriële eigendomsrechten van Producten overdraagt aan Cliënt, verleent Cliënt reeds nu voor alsdan aan Mostpros het exclusieve en niet-herroepbare recht voor het hergebruiken van technische oplossingen en werkwijzen, ideeën en ervaring die Mostpros heeft opgedaan bij ontwikkeling van de Producten. Onder dit recht vallen uitdrukkelijk niet de gegevens van Cliënt in de Producten zelf. Verder zal Mostpros op verzoek van Cliënt naar Cliënt herleidbare gegevens uit Producten anonimiseren of verwijderen.</p>
       <p>15.5. De intellectuele eigendomsrechten, industriële eigendomsrechten en andere rechten van een Product, dan wel een gedeelte daarvan, kunnen slechts middels schriftelijke akte overgedragen indien de betreffende overdragende partij deze rechten heeft.</p>
       <p>15.6. Het is Cliënt respectievelijk Mostpros niet toegestaan enige aanduiding omtrent intellectuele eigendomsrechten, industriële eigendomsrechten, andere rechten, merken en handelsnamen uit de Producten, waaronder het Maatwerk, te verwijderen of te wijzigen, dan wel door een derde dergelijke handelingen te laten verrichten.</p>
       <p>15.7. Indien Mostpros, Cliënt dan wel derden functionele verbeteringen dan wel andere wijzigingen in de Producten, aanbrengen, blijven de op de verbeterde dan wel gewijzigde Producten rustende intellectuele eigendomsrechten, industriële eigendomsrechten en andere rechten in casu ongewijzigd bij Mostpros, bij Maatwerk respectievelijk Cliënt, dan wel de derde rechthebbende berusten.</p>
       <p>15.8. Het is Mostpros toegestaan technische maatregelen te nemen ter bescherming van de Producten of programmatuur of met het oog op overeengekomen beperkingen in de duur van het recht tot gebruik van de Producten of programmatuur. Het is Cliënt niet toegestaan om een dergelijke technische maatregel te verwijderen of te ontwijken. Indien beveiligingsmaatregelen tot gevolg hebben dat Cliënt geen reservekopie van Producten of programmatuur kan maken, zal Mostpros Cliënt desgevraagd een reservekopie ter beschikking stellen.</p>
       <strong>16. Gebruiksrechten</strong>
       <p>16.1. Ten aanzien van Producten en programmatuur die geen Maatwerk zijn, verkrijgt Cliënt een niet-exclusief recht om gebruik te maken van Producten geleverd door Mostpros. Cliënt is gerechtigd dit niet-exclusieve gebruiksrecht over te dragen na toestemming van Mostpros, welke toestemming niet op onredelijke gronden zal onthouden. Ingeval van faillissement van cliënt, ontbinding, vernietiging van een overeenkomst tot levering van het Product vervalt het recht tot gebruik van aan het Cliënt ter beschikking gestelde Product van rechtswege</p>
       <p>16.2. Het gebruiksrecht voor Producten, niet zijnde Maatwerk, is beperkt tot de objectcode. Rechten op en de Broncode(s) zelf worden niet verstrekt, tenzij partijen uitdrukkelijk schriftelijk anders overeenkomen.</p>
       <p>16.3. Het gebruiksrecht omvat niet ongeschreven of niet-overeengekomen, hetzij nieuwe functionaliteit of toepassingsmogelijkheden die het gevolg zijn van (technologische) ontwikkelingen bij Cliënt, Mostpros of in de stand der wetenschap. Op schriftelijke verzoek onderzoekt Mostpros of de beoogde nieuwe functionaliteit of toepassingsmogelijkheden veilig en wenselijk zijn, en kan Mostpros voorwaarden, zoals betaling van een aanvullende vergoeding door Cliënt aan Mostpros of (technische) randvoorwaarden stellen.</p>
       <p>16.4. Het is Cliënt en bij Maatwerk Mostpros verboden de Producten op welke wijze dan ook zelf en/of middels derden, onder welke titel dan ook of op welke wijze dan ook te kopiëren, verspreiden of te openbaren, zonder daaraan voorafgaand de schriftelijke toestemming van Mostpros, bij Maatwerk Cliënt, te hebben ontvangen, behoudens vigerende dwingrechtelijke wetgeving.</p>
       <p>16.5. Behoudens het Maatwerk zal Cliënt de Producten niet wijzigen behalve dan in het kader van het herstellen van Storingen waarbij herstel uitsluitend ziet op de oorspronkelijke staat waarin het Product zich bevond. Mostpros zal het Maatwerk, zonder voorafgaande schriftelijke goedkeuring van Cliënte, niet wijzigen behalve dan in het kader van het herstellen van Storingen en/of het verrichten van onderhoudswerkzaamheden, of op grond van een overeenkomst tussen partijen. Indien Cliënt het Maatwerk wijzigt is uitsluitend Cliënt verantwoordelijk voor de wijzigingen en de gevolgen daarvan.</p>    
       <p>16.6. Het is Cliënt toegestaan Back-ups te maken van zijn gegevens op de ter beschikking gestelde Producten, indien een Back-up niet ter beschikking wordt gesteld door Mostpros en mits de Back-ups niet gebruikt worden door Cliënt voor andere doeleinden dan het duurzaam opslaan van gegevens op een exemplaar voor archiefdoeleinden.</p>
       <p>16.7. Indien Mostpros een gebruiksrecht via een licentie-constructie verstrekt geldt in aanvulling op de voorgaande leden het volgende:</p>
       <p>16.7.1. het daarin vervatte gebruiksrecht wordt beperkt tot uitsluitend het voor door Mostpros toegestane gebruik aanwenden van de Producten op de met Mostpros voor de overeengekomen intensiteit/verwerkingseenheden en op het aantal overeengekomen apparaten, waarbij bij gebreke van schriftelijke afspraken met Mostpros het gebruiksrecht beperkt tot de verwerkingseenheid waarop de Producten het eerst zijn geïnstalleerd en het aantal gebruikers, servers of hardware is beperkt tot 1 (één).</p>
       <p>16.7.2. indien Mostpros in Producten beveiliging of restricties op aantallen verwerkingen, gebruikers of functionaliteit heeft aangebracht is het Cliënt niet toegestaan deze te omzeilen, verwijderen of het beoogde effect anderszins te ontnemen.</p>
       <strong>17. Overmacht</strong>    
       <p>17. Overmacht</p>
       <p>17.2. Indien de overmachttoestand dertig dagen heeft geduurd hebben beide partijen het recht de overeenkomst te ontbinden. In geval van overmacht heeft Cliënt geen recht op schadevergoeding, ook niet als Mostpros enig voordeel mocht hebben. Alle Producten die Mostpros heeft geleverd, kosten die Mostpros tot dan toe heeft gemaakt en kosten voortvloeiend uit verbintenissen met onderaannemers, producenten en derden die zij voor de Producten is aangegaan, worden in elk geval door het moment van ontbinding terstond opeisbaar en afgerekend.</p>
       <p>18. Beëindiging</p>
       <p>18.1. Cliënt komt de bevoegdheid tot ontbinding van een overeenkomst slechts toe indien Mostpros, steeds in alle gevallen na een deugdelijke en zo gedetailleerd mogelijke schriftelijke ingebrekestelling waarbij een redelijke termijn gesteld wordt voor zuivering van de tekortkoming, toerekenbaar tekortschiet in de nakoming van wezenlijke verplichtingen uit de overeenkomst. Indien tussentijdse ontbinding schriftelijk is overeengekomen zullen partijen de vooraf overeengekomen opzegtermijnen en voorschriften steeds in acht nemen.</p>
       <p>18.2. Indien Mostpros met een cliënt een overeenkomst aangaat zal bij tussentijdse beëindiging van de overeenkomst door Cliënt de al verrichte werkzaamheden, kosten die Mostpros tot dan toe heeft gemaakt, vermeerderd met de gemiste bruto winst die Mostpros zou hebben gemaakt bij voltooiing van de overeenkomst indien tussentijdse beëindiging niet zou hebben plaatsgevonden, en kosten voortvloeiend uit verbintenissen met onderaannemers, producenten en derden die zij voor de Producten is aangegaan, onmiddellijke opeisbaar worden. Bij berekening van het factuurbedrag zullen de al verrichte werkzaamheden, indien niet reeds gespecificeerd naar rato worden gefactureerd.</p>
       <p>18.3. Partijen hebben het recht de overeenkomst met de wederpartij met onmiddellijke ingang zonder rechterlijke tussenkomst te ontbinden, zonder daarbij gehouden te zijn tot enige schadevergoeding indien wederpartij in staat van faillissement wordt verklaard, dan wel in surseance van betaling verkeerd, of indien wederpartij wordt geliquideerd of beëindigd anders dan ten behoeve van reconstructie of samenvoeging van ondernemingen.</p>
       <strong>19. Slotbepalingen</strong>
       <p>19.1. Op alle overeenkomsten waarop de Algemene Voorwaarden Mostpros van toepassing zijn is het Nederlands recht van toepassing. Partijen verklaren dat het Weens Koopverdrag (CISG) uitdrukkelijk niet van toepassing is t.a.v. voornoemde overeenkomsten.</p>
       <p>19.2. Voor zover door de regels van dwingend recht niet anders wordt voorgeschreven, zullen alle geschillen die mochten ontstaan naar aanleiding van de overeenkomst worden voorgelegd aan de bevoegde Nederlandse rechter.</p>
       <p>19.3. Mostpros heeft het recht deze Algemene Voorwaarden te wijzigen. Een wijziging zal niet eerder in werking treden dan veertien dagen na kennisgeving aan Cliënt. Cliënt kan de overeenkomst opzeggen tegen de datum dat een dergelijke wijziging van kracht wordt. Aangegane projecten met Cliënt zullen naar rato worden afgerekend.</p>
       <p>19.4. Overdracht van rechten of een overeenkomst aan een derde partij, waaronder begrepen moeder-, zuster- of dochtermaatschappijen is pas toegestaan nadat Cliënt de toestemming van Mostpros verkrijgt voor overdracht aan die derde partij. Deze toestemming zal Mostpros niet op onredelijke gronden onthouden, maar aan het verlenen van toestemming mag Mostpros nadere voorwaarden zoals de betaling van een vergoeding stellen. Cliënt vrijwaart Mostpros voor eventuele aanspraken van derden, die in verband met het overgedragen gebruiksrecht op het Product of door gebruik schade lijden welke aan Mostpros toerekenbaar zouden zijn.</p>
       <p>19.5. Mostpros streeft bij haar dienstverlening naar een adequate opvolging van de ontvangen meldingen en berichten van Cliënt. Om effectief diensten te kunnen leveren zorgt Cliënt voor een steeds bereikbare en voldoende bevoegde contactpersoon; hij/zij speelt o.a. een belangrijke rol bij het voeren van beheer en melden van Storingen. Meldingen (van Storingen) kunnen alleen op de door Mostpros aangegeven wijze. Als een melding buiten werkdagen wordt ontvangen wordt deze de eerstvolgende werkdag geacht te zijn ontvangen. De tijd buiten Werkdagen telt niet mee voor de reactietijd. Afhankelijk van de aard van de melding onderneemt Mostpros actie of reageert naar de contactpersoon.</p>
       <p>19.6. Cliënt geeft Mostpros bij voorbaat het recht, zonder de uitdrukkelijke toestemming van Cliënt nodig te hebben, om overeenkomst(en) dan wel onderdelen daarvan over te dragen aan moeder-, zuster- of dochtermaatschappijen; of een derde partij in het geval van fusie of overname van Mostpros. Indien dit geschiedt zal Mostpros Cliënt hieromtrent informeren.</p>
       <p>19.7. Indien een artikel uit deze overeenkomst niet van toepassing verklaard wordt blijven de overige artikelen hun werking behouden. De rechten en plichten voortvloeiende uit het niet van toepassing verklaarde gedeelte van de overeenkomst zullen zoveel mogelijk vastgesteld worden op dezelfde wijze als de wijze waarop het in het niet van toepassing verklaarde artikel was bedoeld.</p>
    </div>

    </>
    )       
}

export default AVContent;
  