export const specialists = [
    { id: 1, title: 'Aannemer', value: 250 },
    { id: 2, title: 'AI_home_adviseur', value: 350 },
    { id: 3, title: 'Badkamerspecialist', value: 400 },
    { id: 4, title: 'Beveiligingsspecialist', value: 300 },
    { id: 5, title: 'Behanger', value: 300 },
    { id: 6, title: 'Dakdekker', value: 350 },
    { id: 7, title: 'Domotica specialist', value: 400 },
    { id: 8, title: 'Drone-piloot', value: 300 },
    { id: 9, title: 'Elektricien', value: 350 },
    { id: 10, title: 'Exterieur-schilder', value: 300 },
    { id: 11, title: 'Gevelspecialist', value: 400 },
    { id: 12, title: 'Glaszetter', value: 350 },
    { id: 13, title: 'Hovenier', value: 300 },
    { id: 14, title: 'Interieuradviseur', value: 400 },
    { id: 15, title: 'Interieurschilder', value: 350 },
    { id: 16, title: 'Isolatiespecialist', value: 300 },
    { id: 17, title: 'Keukenmonteur', value: 400 },
    { id: 18, title: 'Kozijnspecialist', value: 350 },
    { id: 19, title: 'Loodgieter', value: 300 },
    { id: 20, title: 'Metselaar', value: 400 },
    { id: 21, title: 'Ongediertebestrijder', value: 350 },
    { id: 22, title: 'Robot adviseur', value: 300 },
    { id: 23, title: 'Schoonmaker', value: 400 },
    { id: 24, title: 'Slotenmaker', value: 350 },
    { id: 25, title: 'Smart-garden-adviseur', value: 300 },
    { id: 26, title: 'Smarthome-specialist', value: 400 },
    { id: 27, title: 'Stoffeerder', value: 350 },
    { id: 28, title: 'Stratenmaker', value: 300 },
    { id: 29, title: 'Tegelzetter', value: 400 },
    { id: 30, title: 'Timmerman', value: 350 },
    { id: 31, title: 'Toegangsspecialist', value: 300 },
    { id: 32, title: 'Tuinontwerper', value: 400 },
    { id: 33, title: 'Tuintechnicus', value: 350 },
    { id: 34, title: 'Verduurzamingsadviseur', value: 300 },
    { id: 35, title: 'Verhuizer', value: 400 },
    { id: 36, title: 'Verwarmingsinstallateur', value: 350 },
    { id: 37, title: 'Voertuig-monteur', value: 300 },
    { id: 38, title: 'Zonnepaneel-specialist', value: 400 },
    { id: 39, title: 'Zwembadinstallateur', value: 350 }
];
