export const specialists = [
    { id: 1, title: 'Loodgieter' },
    { id: 2, title: 'Hovenier' },
    { id: 3, title: 'Dakdekker' },
    { id: 4, title: 'Schoonmaker' },
    { id: 5, title: 'Aannemer' },
    { id: 6, title: 'Elektricien' },
    { id: 7, title: 'Interieuradviseur' },
    { id: 8, title: 'Timmerman' },
    { id: 9, title: 'Interieurschilder' },
    { id: 11, title: 'Behanger' },
    { id: 12, title: 'Keukenmonteur' },
    { id: 13, title: 'Tegelzetter' },
    { id: 14, title: 'Badkamerspecialist' },
    { id: 15, title: 'Verwarmingsinstallateur' },
    { id: 16, title: 'Stoffeerder' },
    { id: 17, title: 'Exterieur schilder' },
    { id: 18, title: 'Gevelspecialist' },
    { id: 19, title: 'Isolatiespecialist' },
    { id: 21, title: 'Metselaar' },
    { id: 22, title: 'Glaszetter' },
    { id: 23, title: 'Kozijnspecialist' },
    { id: 24, title: 'Beveiligingsspecialist' },
    { id: 25, title: 'Toegangsspecialist' },
    { id: 26, title: 'Tuinontwerper' },
    { id: 27, title: 'Stratenmaker' },
    { id: 28, title: 'Tuintechnicus' },
    { id: 29, title: 'Zwembadinstallateur' },
    { id: 30, title: 'Smart garden adviseur' },
    { id: 31, title: 'Verhuizer' },
    { id: 32, title: 'Slotenmaker' },
    { id: 33, title: 'Zonnepaneel specialist' },
    { id: 34, title: 'Verduurzamingsadviseur' },
    { id: 35, title: 'Ongediertebestrijder' },
    { id: 36, title: 'Voertuig monteur' },
    { id: 37, title: 'Domotica specialist' },
    { id: 38, title: 'Smarthome specialist' },
    { id: 39, title: 'AI home adviseur' },
    { id: 40, title: 'Drone piloot' },
    { id: 41, title: 'Robot adviseur' },   
];