interface JobDetails {
    title: string;
    description: string;
    trial: string;
    technologies: string[];  // Changed to array of strings
    requirements: string[];
    offer: string[];
    whatweask: string[];
    apply: string;
    extrainfo: string[];
}

const jobsDescription: Record<string, JobDetails> = {
    "HR_IT_Recruiter": {
        title: "HR - IT Recruiter",
        description: "This is a remote/hybrid position.  Currently we are forming the people team and looking for HR - IT Recruiters. We're open for intern and trainee HR - IT Recruiters.",
        trial: "First of all, we will jointly look at how we can set up a win-win situation to become a permanent member of our team. Then we start with a trial period of 1 to 6 months.",
        technologies: [
            "Frontend: React (Native)",
            "Backend: Node.js",
            "Client platforms: iOS, Android, Web",
            "Datastores: DynamoDB",
            "Monitoring: CloudWatch",
            "Infra/cloud: AWS, Cloud Agnostic",
            "Version control: Github",
            "Tools: Slack, Asana, Stripe, Jira, Confluence",
        ],
        requirements: [
            "ML, AI, Python, BI",
            "Quality assurance",
            "Auto/ Manual testing",
            "Devops, Cloud mgmt",
            "Infrastr. automation",
            "Continuous integration & deployment",
            "Cyber security testing",
        ],
        offer: [
            "Fee for trial/intern period. After that a fee possible €XXXX and/or stocks depending on your skills and experience",
            "Knowledge, tools, community and training to be healthy, safe and future-proof all year round;",
            "An important role within a team of experienced digital thinkers and doers;",
            "A company that helps individuals, organizations and stakeholders grow their business through digital growth expertise;",
            "Fun and informal team members with our team and plenty of development opportunities!",
        ],
        whatweask: [
            "Pre if you have university working and thinking level;",
            "Pre if you have 1 - 5+ Years experience as a HR - IT recruiter",
            "Excellent communication skills",
            "Good knowledge in IT Recruitment",
            "Sourcing the right candidates through Job portals, Advertisements, Headhunting, Networking & Employee referrals, etc.",
            "To be good at analytics and proficient in hiring through various channels, job portals, free job posting sites, social networking sites, etc.",
            "Understanding the requirements for sourcing, screening profiles, and shortlisting the candidates for a preliminary interview.",
            "Develop successful sourcing strategies to reach out to passive and active job seekers.",
            "Build good rapport with candidates throughout the interview process to ensure a positive experience.",
            "Regularly update the internal database with new resumes and bring in more innovative recruiting techniques.",
            "Good logical thinking and problem-solving skills",
            "You are very interested in everything related to the domain;",
            "You are meticulous, loyal, energetic, intelligent, diligent and a problem solver!",
        ],
        apply: "Are you the perfect candidate for this position and do you meet the requirements? Then apply and we will contact you as soon as possible!",
        extrainfo: [
            "Education: All levels/ University",
            "Place: Haarlem - The Netherlands, Hybrid or Remote",
            "Working hours per week: 10 - 40+",
            "Employment: Internship, Traineeship, Freelance & Contract...",
            "Responsible for: In consultation.",
        ],
    },
    Software_Engineer: {
        title: "Software Engineer (Javascript, AWS, Fullstack)",
        description: "This is a remote/hybrid position. Currently we are forming the core development team and looking for javascript software engineers (fullstack). We're open for intern and trainee software engineers.",
        trial: "First of all, we will jointly look at how we can set up a win-win situation to become a permanent member of our team. Then we start with a trial period of 1 to 6 months.",
        technologies: [
            "Frontend: React (Native)",
            "Backend: Node.js",
            "Client platforms: iOS, Android, Web",
            "Datastores: DynamoDB",
            "Monitoring: CloudWatch",
            "Infra/cloud: AWS, Cloud Agnostic",
            "Version control: Github",
            "Tools:  Slack, Asana, Stripe",
        ],
        requirements: [
            "ML, AI, Python, BI",
            "Quality assurance",
            "Auto/ Manual testing",
            "Devops, Cloud mgmt",
            "Infrastr. automation",
            "Continuous integration & deployment",
            "Cyber security testing",
        ],
        offer: [
            "Fee for trial/intern period. After that a fee possible €XXXX and/or stocks depending on your skills and experience",
            "Knowledge, tools, community and training to be healthy, safe and future-proof all year round;",
            "An important role within a team of experienced digital thinkers and doers;",
            "A company that helps individuals, organizations and stakeholders grow their business through digital growth expertise;",
            "Fun and informal team members with our team and plenty of development opportunities!",
        ],
        whatweask: [
            "Pre if you have university working and thinking level;",
            "Pre if you have 0.5 - 5+ Years experience as a HR - IT recruiter",
            "Good understanding of structured and unstructured databases (MySQL and DynamoDB)",
            "Knowledge of isomorphic React is an added advantage",
            "Experience in implementing well-known React workflows",
            "Experience with Javascript backend framework like node.js",
            "Ability to learn new technologies and languages quickly",
            "Good time-management skills",
            "Experience with Restful API services",
            "Delivering a complete front end application",
            "Professional, precise communication skills",
            "Deep knowledge of Angular/Node.js/React practices and commonly used modules based on extensive work experience",
            "Good knowledge in Javascript and able to handle Array & Objects built-in methods",
            "Good logical thinking and problem-solving skills",
            "A good team player",
            "You are very interested in everything related to the domain;",
            "You are meticulous, loyal, energetic, intelligent, diligent and a problem solver!",
        ],
        apply: "Are you the perfect candidate for this position and do you meet the requirements? Then apply and we will contact you as soon as possible!",
        extrainfo: [
            "Education: All levels/ University",
            "Place: Haarlem - The Netherlands, Hybrid or Remote",
            "Working hours per week: 10 - 40+",
            "Employment: Internship, Traineeship, Freelance & Contract...",
            "Responsible for: In consultation.",
        ]
    },
    Software_Tester: {
        title: "Software Tester",
        description: "This is a remote/hybrid position. Currently we are forming the core development team and looking for software testers. We're open for intern and trainee software testers.",
        trial: "First of all, we will jointly look at how we can set up a win-win situation to become a permanent member of our team. Then we start with a trial period of 1 to 6 months.",
        technologies: [
            "Frontend: React (Native)",
            "Backend: Node.js",
            "Client platforms: iOS, Android, Web",
            "Datastores: DynamoDB",
            "Monitoring: CloudWatch",
            "Infra/cloud: AWS, Cloud Agnostic",
            "Version control: Github",
            "Tools: Slack, Asana, Stripe, Jira, Confluence",
        ],
        requirements: [
            "ML, AI, Python, BI",
            "Quality assurance",
            "Auto/ Manual testing",
            "Devops, Cloud mgmt",
            "Infrastr. automation",
            "Continuous integration & deployment",
            "Cyber security testing",
        ],
        offer: [
            "Fee for trial/intern period. After that a fee possible €XXXX and/or stocks depending on your skills and experience",
            "Knowledge, tools, community and training to be healthy, safe and future-proof all year round;",
            "An important role within a team of experienced digital thinkers and doers;",
            "A company that helps individuals, organizations and stakeholders grow their business through digital growth expertise;",
            "Fun and informal team members with our team and plenty of development opportunities!",
        ],
        whatweask: [
            "Pre if you have university working and thinking level;",
            "Pre if you have 0,5 - 5+ Years experience as a HR - IT recruiter",
            "Good knowledge in manual testing",
            "Good knowledge in test case preparation",
            "Good written and verbal communication skills",
            "Strong analytical and documentation skills to present findings to team members",
            "Analyze requirements for validity and feasibility",
            "Execute all levels of testing",
            "Detect, track defects and inconsistencies",
            "Good logical thinking and problem-solving skills",
            "A good team player",
            "You are very interested in everything related to the domain;",
            "You are meticulous, loyal, energetic, intelligent, diligent and a problem solver!",
        ],
        apply: "Are you the perfect candidate for this position and do you meet the requirements? Then apply and we will contact you as soon as possible!",
        extrainfo: [
            "Education: All levels/ University",
            "Place: Haarlem - The Netherlands, Hybrid or Remote",
            "Working hours per week: 10 - 40+",
            "Employment: Internship, Traineeship, Freelance & Contract...",
            "Responsible for: In consultation.",
        ],
    },
    Business_Analyst: {
        title: "Business Analyst",
        description: "This is a remote/hybrid position. Currently we are forming the core development team and looking for business analysts.We're open for intern and trainee business analysts.",
        trial: "First of all, we will jointly look at how we can set up a win-win situation to become a permanent member of our team. Then we start with a trial period of 1 to 6 months.",
        technologies: [
            "Frontend: React (Native)",
            "Backend: Node.js",
            "Client platforms: iOS, Android, Web",
            "Datastores: DynamoDB",
            "Monitoring: CloudWatch",
            "Infra/cloud: AWS, Cloud Agnostic",
            "Version control: Github",
            "Tools: Slack, Asana, Stripe, Jira, Confluence",
        ],
        requirements: [
            "ML, AI, Python, BI",
            "Quality assurance",
            "Auto/ Manual testing",
            "Devops, Cloud mgmt",
            "Infrastr. automation",
            "Continuous integration & deployment",
            "Cyber security testing",
        ],
        offer: [
            "Fee for trial/intern period. After that a fee possible €XXXX and/or stocks depending on your skills and experience",
            "Knowledge, tools, community and training to be healthy, safe and future-proof all year round;",
            "An important role within a team of experienced digital thinkers and doers;",
            "A company that helps individuals, organizations and stakeholders grow their business through digital growth expertise;",
            "Fun and informal team members with our team and plenty of development opportunities!",
        ],
        whatweask: [
            "Pre if you have university working and thinking level;",
            "Pre if you have 0,5 - 5+ Years experience as a business developer",
            "Excellent communication skills",
            "Documentation skills",
            "Understanding and capturing business needs, requirement analysis process",
            "Analyzing the business to understand the model of the business",
            "Basic knowledge about Jira tool, Agile methodology would be an added advantage",
            "Good logical thinking and problem-solving skills",
            "A good team player",
            "You are very interested in everything related to the domain;",
            "You are meticulous, loyal, energetic, intelligent, diligent and a problem solver!",
        ],
        apply: "Are you the perfect candidate for this position and do you meet the requirements? Then apply and we will contact you as soon as possible!",
        extrainfo: [
            "Education: All levels/ University",
            "Place: Haarlem - The Netherlands, Hybrid or Remote",
            "Working hours per week: 10 - 40+",
            "Employment: Internship, Traineeship, Freelance & Contract...",
            "Responsible for: In consultation.",
        ],
    },
    IOS_Android_Dev: {
        title: "IOS/Android Developer",
        description: "This is a remote/hybrid position. Currently we are forming the core development team and looking for iOS/Android developers. We're open for intern and trainee iOS/Android developers.",
        trial: "First of all, we will jointly look at how we can set up a win-win situation to become a permanent member of our team. Then we start with a trial period of 1 to 6 months.",
        technologies: [
            "Frontend: React (Native)",
            "Backend: Node.js",
            "Client platforms: iOS, Android, Web",
            "Datastores: DynamoDB",
            "Monitoring: CloudWatch",
            "Infra/cloud: AWS, Cloud Agnostic",
            "Version control: Github",
            "Tools: Slack, Asana, Stripe, Jira, Confluence",
        ],
        requirements: [
            "ML, AI, Python, BI",
            "Quality assurance",
            "Auto/ Manual testing",
            "Devops, Cloud mgmt",
            "Infrastr. automation",
            "Continuous integration & deployment",
            "Cyber security testing",
        ],
        offer: [
            "Fee for trial/intern period. After that a fee possible €XXXX and/or stocks depending on your skills and experience",
            "Knowledge, tools, community and training to be healthy, safe and future-proof all year round;",
            "An important role within a team of experienced digital thinkers and doers;",
            "A company that helps individuals, organizations and stakeholders grow their business through digital growth expertise;",
            "Fun and informal team members with our team and plenty of development opportunities!",
        ],
        whatweask: [
            "Pre if you have university working and thinking level;",
            "Pre if you have 0,5 - 5+ Years experience as a Software Engineer",
            "Good understanding of structured and unstructured databases (MySQL and DynamoDB)",
            "Knowledge of tech stack is an added advantage",
            "Experience in implementing well-known workflows",
            "Ability to learn new technologies and languages quickly",
            "Proficient understanding of code versioning tools, such as Git",
            "Experience with Javascript backend framework",
            "Good time-management skills",
            "Experience with Restful API services",
            "Professional, precise communication skills",
            "Deep knowledge of Angular/Node.js/React practices and commonly used modules based on extensive work experience",
            "Good logical thinking and problem-solving skills",
            "A good team player",
            "You are very interested in everything related to the domain;",
            "You are meticulous, loyal, energetic, intelligent, diligent and a problem solver!",
        ],
        apply: "Are you the perfect candidate for this position and do you meet the requirements? Then apply and we will contact you as soon as possible!",
        extrainfo: [
            "Education: All levels/ University",
            "Place: Haarlem - The Netherlands, Hybrid or Remote",
            "Working hours per week: 10 - 40+",
            "Employment: Internship, Traineeship, Freelance & Contract...",
            "Responsible for: In consultation.",
        ],
    },
    UX_UI_Designer: {
        title: "UX/UI Designer",
        description: "This is a remote/hybrid position. Currently we are forming the core development team and looking for UX/UI designers. We're open for intern and trainee UX/UI designers.",
        trial: "First of all, we will jointly look at how we can set up a win-win situation to become a permanent member of our team. Then we start with a trial period of 1 to 6 months.",
        technologies: [
            "Frontend: React (Native)",
            "Backend: Node.js",
            "Client platforms: iOS, Android, Web",
            "Datastores: DynamoDB",
            "Monitoring: CloudWatch",
            "Infra/cloud: AWS, Cloud Agnostic",
            "Version control: Github",
            "Tools: Slack, Asana, Stripe, Jira, Confluence",
        ],
        requirements: [
            "ML, AI, Python, BI",
            "Quality assurance",
            "Auto/ Manual testing",
            "Devops, Cloud mgmt",
            "Infrastr. automation",
            "Continuous integration & deployment",
            "Cyber security testing",
        ],
        offer: [
            "Fee for trial/intern period. After that a fee possible €XXXX and/or stocks depending on your skills and experience",
            "Knowledge, tools, community and training to be healthy, safe and future-proof all year round;",
            "An important role within a team of experienced digital thinkers and doers;",
            "A company that helps individuals, organizations and stakeholders grow their business through digital growth expertise;",
            "Fun and informal team members with our team and plenty of development opportunities!",
        ],
        whatweask: [
            "Pre if you have university working and thinking level;",
            "Pre if you have 1 - 5+ Years experience as a UX/UI Designer",
            "Excellent communication skills",
            "UX/UI Designing, Figma, Adobe Photoshop, Video Editing, Gif Animation, Adobe After Effects, Premier Pro",
            "Design and create videos like app explainer videos, product videos, 2D animation videos, corporate videos, etc",
            "Excellent proficiency in After Effects, Premier Pro, Illustrator, Corel Draw, Adobe Photoshop",
            "Think creatively and develop new design concepts, graphics, and layouts",
            "Prior working experience on Adobe After Effects, Premiere pro, Illustrator or similar tools",
            "Good understanding of current design trends for both Mobile and Web and be able to create seamless experiences across all platforms",
            "Good foundation in graphic design principles, typography, color, and styles",
            "Adapt quickly to the changes and deliver results",
            "A good team player",
            "You are very interested in everything related to the domain;",
            "You are meticulous, loyal, energetic, intelligent, diligent and a problem solver!",
        ],
        apply: "Are you the perfect candidate for this position and do you meet the requirements? Then apply and we will contact you as soon as possible!",
        extrainfo: [
            "Education: All levels/ University",
            "Place: Haarlem - The Netherlands, Hybrid or Remote",
            "Working hours per week: 10 - 40+",
            "Employment: Internship, Traineeship, Freelance & Contract...",
            "Responsible for: In consultation.",
        ],
    },
    DevOps_Engineer: {
        title: "DevOps Engineer",
        description: "This is a remote/hybrid position. Currently we are forming the core development team and looking for DevOps engineers. We're open for intern and trainee DevOps engineers.",
        trial: "First of all, we will jointly look at how we can set up a win-win situation to become a permanent member of our team. Then we start with a trial period of 1 to 6 months.",
        technologies: [
            "Frontend: React (Native)",
            "Backend: Node.js",
            "Client platforms: iOS, Android, Web",
            "Datastores: DynamoDB",
            "Monitoring: CloudWatch",
            "Infra/cloud: AWS, Cloud Agnostic",
            "Version control: Github",
            "Tools: Slack, Asana, Stripe, Jira, Confluence",
        ],
        requirements: [
            "ML, AI, Python, BI",
            "Quality assurance",
            "Auto/ Manual testing",
            "Devops, Cloud mgmt",
            "Infrastr. automation",
            "Continuous integration & deployment",
            "Cyber security testing",
        ],
        offer: [
            "Fee for trial/intern period. After that a fee possible €XXXX and/or stocks depending on your skills and experience",
            "Knowledge, tools, community and training to be healthy, safe and future-proof all year round;",
            "An important role within a team of experienced digital thinkers and doers;",
            "A company that helps individuals, organizations and stakeholders grow their business through digital growth expertise;",
            "Fun and informal team members with our team and plenty of development opportunities!",
        ],
        whatweask: [
            "Pre if you have university working and thinking level;",
            "Pre if you have 1 - 5 + Years experience as a DevOps engineer",
            "Excellent communication skills",
            "Documentation skills",
            "Deploying applications in a DevOps environments",
            "Hands- on experience with Popular CI/ CD tools like [Jenkins, Docker, Kubernetes]",
            "Good knowledge on Scripting[Javascript, React, Node.js]",
            "Knowledge on MySQL and NoSQL database administration",
            "Familiar with AWS and other DevOps concepts",
            "Familiar with the DevOps commands",
            "Working knowledge and experience on open source tools, version controls[GIT]",
            "Good logical thinking and problem - solving skills",
            "A good team player",
            "You are very interested in everything related to the domain;",
            "You are meticulous, loyal, energetic, intelligent, diligent and a problem solver!",
        ],
        apply: "Are you the perfect candidate for this position and do you meet the requirements? Then apply and we will contact you as soon as possible!",
        extrainfo: [
            "Education: All levels/ University",
            "Place: Haarlem - The Netherlands, Hybrid or Remote",
            "Working hours per week: 10 - 40+",
            "Employment: Internship, Traineeship, Freelance & Contract...",
            "Responsible for: In consultation.",
        ],
    },
    Product_Owner: {
        title: "Product Owner",
        description: "This is a remote/hybrid position. Currently we are forming the core development team and looking for Product Owners. We're open for intern and trainee Product Owners.",
        trial: "First of all, we will jointly look at how we can set up a win-win situation to become a permanent member of our team. Then we start with a trial period of 1 to 6 months.",
        technologies: [
            "Frontend: React (Native)",
            "Backend: Node.js",
            "Client platforms: iOS, Android, Web",
            "Datastores: DynamoDB",
            "Monitoring: CloudWatch",
            "Infra/cloud: AWS, Cloud Agnostic",
            "Version control: Github",
            "Tools: Slack, Asana, Stripe, Jira, GitHub",
        ],
        requirements: [
            "ML, AI, Python, BI",
            "Quality assurance",
            "Auto/ Manual testing",
            "Devops, Cloud mgmt",
            "Infrastr. automation",
            "Continuous integration & deployment",
            "Cyber security testing",
        ],
        offer: [
            "Fee for trial/intern period. After that a fee possible €XXXX and/or stocks depending on your skills and experience",
            "Knowledge, tools, community and training to be healthy, safe and future-proof all year round;",
            "An important role within a team of experienced digital thinkers and doers;",
            "A company that helps individuals, organizations and stakeholders grow their business through digital growth expertise;",
            "Fun and informal team members with our team and plenty of development opportunities!",
        ],
        whatweask: [
            "Pre if you have university working and thinking level;",
            "Pre if you have 0,5 - 5+ Years experience as a product owner or software engineer;",
            "Good understanding of product ownership, management en lifecycle.",
            "Able to fine tune the product vision. Keeps product in line with business goals. Creates a product roadmap. Communicates with stakeholders to understand business objectives.",
            "Able to prioritize needs. Juggles scope, budget, and time to prioritize projects. Considers needs and objectives of stakeholders.",
            "Able to manage the product backlog. Maps out dependencies. Prioritizes items based on overall strategy. Creates a list of backlog items.",
            "Able to oversee development stages. Contributes to the planning, execution, and review of each sprint. Works with team to refine and improve the development process.",
            "Anticipating client needs. Understands and anticipates client needs to manage the development process. Has deep knowledge of the market. Creates customer journey maps.",
            "Able to act as primary liaison. Gains buy-in from stakeholder. Delivers clear instructions to the developers.",
            "Able to evaluate product progress. Is accountable for each stage of the development process and final process. Inspects and evaluates product",
        ],
        apply: "Are you the perfect candidate for this position and do you meet the requirements? Then apply and we will contact you as soon as possible!",
        extrainfo: [
            "Education: All levels/ University",
            "Place: Haarlem - The Netherlands, Hybrid or Remote",
            "Working hours per week: 10 - 40+",
            "Employment: Internship, Traineeship, Freelance & Contract...",
            "Responsible for: In consultation.",
        ],
    },
    Cyber_Security_Engineer: {
        title: "Cyber Security Engineer",
        description: "This is a remote/hybrid position. Currently we are forming the core development team and looking for Cyber Security Engineers. We're open for intern and trainee Cyber Security Engineers.",
        trial: "First of all, we will jointly look at how we can set up a win-win situation to become a permanent member of our team. Then we start with a trial period of 1 to 6 months.",
        technologies: [
            "Frontend: React (Native)",
            "Backend: Node.js",
            "Client platforms: iOS, Android, Web",
            "Datastores: DynamoDB",
            "Monitoring: CloudWatch",
            "Infra/cloud: AWS, Cloud Agnostic",
            "Version control: Github",
            "Tools: Slack, Asana, Stripe, Jira, GitHub",
        ],
        requirements: [
            "ML, AI, Python, BI",
            "Quality assurance",
            "Auto/ Manual testing",
            "Devops, Cloud mgmt",
            "Infrastr. automation",
            "Continuous integration & deployment",
            "Cyber security testing",
        ],
        offer: [
            "Fee for trial/intern period. After that a fee possible €XXXX and/or stocks depending on your skills and experience",
            "Knowledge, tools, community and training to be healthy, safe and future-proof all year round;",
            "An important role within a team of experienced digital thinkers and doers;",
            "A company that helps individuals, organizations and stakeholders grow their business through digital growth expertise;",
            "Fun and informal team members with our team and plenty of development opportunities!",
        ],
        whatweask: [
            "Pre if you have university working and thinking level;",
            "Pre if you have 0,5 - 5+ Years experience as a software engineer;",
            "Good understanding of structured and unstructured databases (MySQL and DynamoDB)",
            "Knowledge of isomorphic React is an added advantage",
            "Experience in implementing well-known React workflows",
            "Ability to learn new technologies and languages quickly",
            "Proficient understanding of code versioning tools, such as Git",
            "Experience with Javascript backend framework like node.js",
            "Knowledge of cyber security red, purple and blue teams",
            "Knowledge of ethical hacking",
            "Knowledge of penetration testing",
            "Good time-management skills",
            "Experience with Restful API services",
            "Delivering a complete front end application",
            "Professional, precise communication skills",
            "Deep knowledge of Angular/Node.js/React practices and commonly used modules based on extensive work experience",
            "Good knowledge in Javascript and able to handle Array & Objects built-in methods",
            "Good logical thinking and problem-solving skills",
            "A good team player",
            "You are very interested in everything related to the domain;",
            "You are meticulous, loyal, energetic, intelligent, diligent and a problem solver!",
        ],
        apply: "Are you the perfect candidate for this position and do you meet the requirements? Then apply and we will contact you as soon as possible!",
        extrainfo: [
            "Education: All levels/ University",
            "Place: Haarlem - The Netherlands, Hybrid or Remote",
            "Working hours per week: 10 - 40+",
            "Employment: Internship, Traineeship, Freelance & Contract...",
            "Responsible for: In consultation.",
        ],
    },
    AI_Data_Engineer: {
        title: "AI Data Engineer",
        description: "This is a remote/hybrid position. Currently we are forming the core development team and looking for AI Data Engineers. We're open for intern and trainee AI Data Engineers.",
        trial: "First of all, we will jointly look at how we can set up a win-win situation to become a permanent member of our team. Then we start with a trial period of 1 to 6 months.",
        technologies: [
            "Frontend: React (Native)",
            "Backend: Node.js",
            "Client platforms: iOS, Android, Web",
            "Datastores: DynamoDB",
            "Monitoring: CloudWatch",
            "Infra/cloud: AWS, Cloud Agnostic",
            "Version control: Github",
            "Tools: Slack, Asana, Stripe, Jira, GitHub",
        ],
        requirements: [
            "ML, AI, Python, BI",
            "Quality assurance",
            "Auto/ Manual testing",
            "Devops, Cloud mgmt",
            "Infrastr. automation",
            "Continuous integration & deployment",
            "Cyber security testing",
        ],
        offer: [
            "Fee for trial/intern period. After that a fee possible €XXXX and/or stocks depending on your skills and experience",
            "Knowledge, tools, community and training to be healthy, safe and future-proof all year round;",
            "An important role within a team of experienced digital thinkers and doers;",
            "A company that helps individuals, organizations and stakeholders grow their business through digital growth expertise;",
            "Fun and informal team members with our team and plenty of development opportunities!",
        ],
        whatweask: [
            "Pre if you have university working and thinking level;",
            "Pre if you have 0,5 - 5+ Years experience as a data engineer;",
            "Good understanding of structured and unstructured databases (MySQL and DynamoDB)",
            "Knowledge of isomorphic React is an added advantage",
            "Experience in implementing well-known React workflows",
            "Ability to learn new technologies and languages quickly",
            "Proficient understanding of code versioning tools, such as Git",
            "Experience with Javascript backend framework like node.js",
            "Good time-management skills",
            "Experience with Restful API services",
            "Delivering a complete front end application",
            "Professional, precise communication skills",
            "Deep knowledge of Angular/Node.js/React practices and commonly used modules based on extensive work experience",
            "Good knowledge in Javascript and able to handle Array & Objects built-in methods",
            "Good logical thinking and problem-solving skills",
            "A good team player",
            "You are very interested in everything related to the domain;",
            "You are meticulous, loyal, energetic, intelligent, diligent and a problem solver!",
        ],
        apply: "Are you the perfect candidate for this position and do you meet the requirements? Then apply and we will contact you as soon as possible!",
        extrainfo: [
            "Education: All levels/ University",
            "Place: Haarlem - The Netherlands, Hybrid or Remote",
            "Working hours per week: 10 - 40+",
            "Employment: Internship, Traineeship, Freelance & Contract...",
            "Responsible for: In consultation.",
        ],
    },
    IoTSoftware_Engineer: {
        title: "IoT Software Engineer",
        description: "This is a remote/hybrid position. Currently we are forming the core development team and looking for Growth Hackers. We're open for intern and trainee Growth Hackers.",
        trial: "First of all, we will jointly look at how we can set up a win-win situation to become a permanent member of our team. Then we start with a trial period of 1 to 6 months.",
        technologies: [
            "Frontend: React (Native)",
            "Backend: Node.js",
            "Client platforms: iOS, Android, Web",
            "Datastores: DynamoDB",
            "Monitoring: CloudWatch",
            "Infra/cloud: AWS, Cloud Agnostic",
            "Version control: Github",
            "Tools: Slack, Asana, Stripe, Jira, GitHub",
        ],
        requirements: [
            "ML, AI, Python, BI",
            "Quality assurance",
            "Auto/ Manual testing",
            "Devops, Cloud mgmt",
            "Infrastr. automation",
            "Continuous integration & deployment",
            "Cyber security testing",
        ],
        offer: [
            "Fee for trial/intern period. After that a fee possible €XXXX and/or stocks depending on your skills and experience",
            "Knowledge, tools, community and training to be healthy, safe and future-proof all year round;",
            "An important role within a team of experienced digital thinkers and doers;",
            "A company that helps individuals, organizations and stakeholders grow their business through digital growth expertise;",
            "Fun and informal team members with our team and plenty of development opportunities!",
        ],
        whatweask: [
            "Pre if you have university working and thinking level;",
            "Pre if you have 0,5 - 5+ Years experience as a IoT software engineer;",
            "Good understanding of structured and unstructured databases (MySQL and DynamoDB)",
            "Knowledge of isomorphic React is an added advantage",
            "Experience in implementing well-known React workflows",
            "Ability to learn new technologies and languages quickly",
            "Proficient understanding of code versioning tools, such as Git",
            "Experience with Javascript backend framework like node.js",
            "Good time-management skills",
            "Experience with Restful API services",
            "Delivering a complete front end application",
            "Professional, precise communication skills",
            "Deep knowledge of Angular/Node.js/React practices and commonly used modules based on extensive work experience",
            "Good knowledge in Javascript and able to handle Array & Objects built-in methods",
            "Good logical thinking and problem-solving skills",
            "A good team player",
            "You are very interested in everything related to the domain;",
            "You are meticulous, loyal, energetic, intelligent, diligent and a problem solver!",
        ],
        apply: "Are you the perfect candidate for this position and do you meet the requirements? Then apply and we will contact you as soon as possible!",
        extrainfo: [
            "Education: All levels/ University",
            "Place: Haarlem - The Netherlands, Hybrid or Remote",
            "Working hours per week: 10 - 40+",
            "Employment: Internship, Traineeship, Freelance & Contract...",
            "Responsible for: In consultation.",
        ],
    },
    GrowthHacker: {
        title: "Growth Hacker",
        description: "This is a remote/hybrid position. Currently we are forming the core growth team and looking for Growth Hackers. We're open for intern and trainee Growth Hackers.",
        trial: "First of all, we will jointly look at how we can set up a win-win situation to become a permanent member of our team. Then we start with a trial period of 1 to 6 months.",
        technologies: [
            "Frontend: React (Native)",
            "Backend: Node.js",
            "Client platforms: iOS, Android, Web",
            "Datastores: DynamoDB",
            "Monitoring: CloudWatch",
            "Infra/cloud: AWS, Cloud Agnostic",
            "Version control: Github",
            "Tools: Slack, Asana, Stripe, Jira, GitHub",
        ],
        requirements: [
            "ML, AI, Python, BI",
            "Quality assurance",
            "Auto/ Manual testing",
            "Devops, Cloud mgmt",
            "Infrastr. automation",
            "Continuous integration & deployment",
            "Cyber security testing",
        ],
        offer: [
            "Fee for trial/intern period. After that a fee possible €XXXX and/or stocks depending on your skills and experience",
            "Knowledge, tools, community and training to be healthy, safe and future-proof all year round;",
            "An important role within a team of experienced digital thinkers and doers;",
            "A company that helps individuals, organizations and stakeholders grow their business through digital growth expertise;",
            "Fun and informal team members with our team and plenty of development opportunities!",
        ],
        whatweask: [
            "Pre if you have university working and thinking level;",
            "Pre if you have 0,5 - 5+ Years experience as a growth hacker",
            "Good written and verbal communication skills",
            "Sound knowledge on the IT Sales",
            "Knowledge about lead generation",
            "Understanding on the inbound and outbound sales process",
            "Logical thinking and ability to explain software features clearly",
            "Good logical thinking and problem-solving skills",
            "A good team player",
            "You are very interested in everything related to the domain;",
            "You are meticulous, loyal, energetic, intelligent, diligent and a problem solver!",
        ],
        apply: "Are you the perfect candidate for this position and do you meet the requirements? Then apply and we will contact you as soon as possible!",
        extrainfo: [
            "Education: All levels/ University",
            "Place: Haarlem - The Netherlands, Hybrid or Remote",
            "Working hours per week: 10 - 40+",
            "Employment: Internship, Traineeship, Freelance & Contract...",
            "Responsible for: In consultation.",
        ],
    },
    Business_Developer: {
        title: "Business Developer",
        description: "This is a remote/hybrid position. Currently we are forming the core growth team and looking for business developers. We're open for intern and trainee business developers.",
        trial: "First of all, we will jointly look at how we can set up a win-win situation to become a permanent member of our team. Then we start with a trial period of 1 to 6 months.",
        technologies: [
            "Frontend: React (Native)",
            "Backend: Node.js",
            "Client platforms: iOS, Android, Web",
            "Datastores: DynamoDB",
            "Monitoring: CloudWatch",
            "Infra/cloud: AWS, Cloud Agnostic",
            "Version control: Github",
            "Tools: Slack, Asana, Stripe, Jira, Confluence",
        ],
        requirements: [
            "ML, AI, Python, BI",
            "Quality assurance",
            "Auto/ Manual testing",
            "Devops, Cloud mgmt",
            "Infrastr. automation",
            "Continuous integration & deployment",
            "Cyber security testing",
        ],
        offer: [
            "Fee for trial/intern period. After that a fee possible €XXXX and/or stocks depending on your skills and experience",
            "Knowledge, tools, community and training to be healthy, safe and future-proof all year round;",
            "An important role within a team of experienced digital thinkers and doers;",
            "A company that helps individuals, organizations and stakeholders grow their business through digital growth expertise;",
            "Fun and informal team members with our team and plenty of development opportunities!",
        ],
        whatweask: [
            "Pre if you have university working and thinking level;",
            "Pre if you have 0,5 - 5+ Years experience as a business developer",
            "Good written and verbal communication skills",
            "Sound knowledge on the IT Sales",
            "Knowledge about lead generation",
            "Understanding on the inbound and outbound sales process",
            "Logical thinking and ability to explain software features clearly",
            "Good logical thinking and problem-solving skills",
            "A good team player",
            "You are very interested in everything related to the domain;",
            "You are meticulous, loyal, energetic, intelligent, diligent and a problem solver!",
        ],
        apply: "Are you the perfect candidate for this position and do you meet the requirements? Then apply and we will contact you as soon as possible!",
        extrainfo: [
            "Education: All levels/ University",
            "Place: Haarlem - The Netherlands, Hybrid or Remote",
            "Working hours per week: 10 - 40+",
            "Employment: Internship, Traineeship, Freelance & Contract...",
            "Responsible for: In consultation.",
        ],
    },
    B2BMarketing_Sales: {
        title: "B2B Marketing & Sales",
        description: "This is a remote/hybrid position. Currently we are forming the core growth team and looking for B2B Marketing & Sales. We're open for intern and trainee B2B Marketing & Sales.",
        trial: "First of all, we will jointly look at how we can set up a win-win situation to become a permanent member of our team. Then we start with a trial period of 1 to 6 months.",
        technologies: [
            "Frontend: React (Native)",
            "Backend: Node.js",
            "Client platforms: iOS, Android, Web",
            "Datastores: DynamoDB",
            "Monitoring: CloudWatch",
            "Infra/cloud: AWS, Cloud Agnostic",
            "Version control: Github",
            "Tools: Slack, Asana, Stripe, Jira, Confluence",
        ],
        requirements: [
            "ML, AI, Python, BI",
            "Quality assurance",
            "Auto/ Manual testing",
            "Devops, Cloud mgmt",
            "Infrastr. automation",
            "Continuous integration & deployment",
            "Cyber security testing",
        ],
        offer: [
            "Fee for trial/intern period. After that a fee possible €XXXX and/or stocks depending on your skills and experience",
            "Knowledge, tools, community and training to be healthy, safe and future-proof all year round;",
            "An important role within a team of experienced digital thinkers and doers;",
            "A company that helps individuals, organizations and stakeholders grow their business through digital growth expertise;",
            "Fun and informal team members with our team and plenty of development opportunities!",
        ],
        whatweask: [
            "Pre if you have university working and thinking level;",
            "Pre if you have 1 - 5+ Years experience as a B2B Marketer, Sales or SEO Analyst",
            "Excellent communication skills",
            "Plan and implement the overall SEO strategy [On & Off-page SEO (Quality backlinks)]",
            "Work with Google Analytics, Google Webmaster & Bing Webmaster tools",
            "Create and manage inbound marketing strategies",
            "Analyze the competition and provide suggestions for improvement",
            "Manage company's social media accounts",
            "Manage and improve the website and social media content",
            "Blogs and landing pages promotion using off and on-page SEO strategies",
            "Keyword generation for both blog and landing pages",
            "Analyze and fix SEO issues on websites",
            "Keep updated with the latest industry trends and ensure that the company is in front of the industry developments",
            "Good logical thinking and problem-solving skills",
            "A good team player",
            "You are very interested in everything related to the domain;",
            "You are meticulous, loyal, energetic, intelligent, diligent and a problem solver!",
        ],
        apply: "Are you the perfect candidate for this position and do you meet the requirements? Then apply and we will contact you as soon as possible!",
        extrainfo: [
            "Education: All levels/ University",
            "Place: Haarlem - The Netherlands, Hybrid or Remote",
            "Working hours per week: 10 - 40+",
            "Employment: Internship, Traineeship, Freelance & Contract...",
            "Responsible for: In consultation.",
        ],
    },
    AI_Data_Marketing_Analyst: {
        title: "AI Data Marketing Analyst",
        description: "This is a remote/hybrid position. Currently we are forming the core growth team and looking for AI Data Marketing Analysts. We're open for intern and trainee AI Data Marketing Analysts.",
        trial: "First of all, we will jointly look at how we can set up a win-win situation to become a permanent member of our team. Then we start with a trial period of 1 to 6 months.",
        technologies: [
            "Frontend: React (Native)",
            "Backend: Node.js",
            "Client platforms: iOS, Android, Web",
            "Datastores: DynamoDB",
            "Monitoring: CloudWatch",
            "Infra/cloud: AWS, Cloud Agnostic",
            "Version control: Github",
            "Tools: Slack, Asana, Stripe, Jira, Confluence",
        ],
        requirements: [
            "ML, AI, Python, BI",
            "Quality assurance",
            "Auto/ Manual testing",
            "Devops, Cloud mgmt",
            "Infrastr. automation",
            "Continuous integration & deployment",
            "Cyber security testing",
        ],
        offer: [
            "Fee for trial/intern period. After that a fee possible €XXXX and/or stocks depending on your skills and experience",
            "Knowledge, tools, community and training to be healthy, safe and future-proof all year round;",
            "An important role within a team of experienced digital thinkers and doers;",
            "A company that helps individuals, organizations and stakeholders grow their business through digital growth expertise;",
            "Fun and informal team members with our team and plenty of development opportunities!",
        ],
        whatweask: [
            "Pre if you have university working and thinking level;",
            "Pre if you have 1 - 5+ Years experience as a Marketing Analyst",
            "Excellent communication skills",
            "As a AI Data Marketing Analyst, you’ll be working closely with the growth team to create valuable insights",
            "Ability to put forth complex AI Data topics in a simpler form.",
            "Strong attention to detail & impeccable grasp of the English language.",
            "Excellent verbal and written communication skills.",
            "Basic knowledge on AI Data and Machine Learning. [Optional]",
            "Good logical thinking and problem-solving skills",
            "A good team player",
            "You are very interested in everything related to the domain;",
            "You are meticulous, loyal, energetic, intelligent, diligent and a problem solver!",
        ],
        apply: "Are you the perfect candidate for this position and do you meet the requirements? Then apply and we will contact you as soon as possible!",
        extrainfo: [
            "Education: All levels/ University",
            "Place: Haarlem - The Netherlands, Hybrid or Remote",
            "Working hours per week: 10 - 40+",
            "Employment: Internship, Traineeship, Freelance & Contract...",
            "Responsible for: In consultation.",
        ],
    },
    Performance_Marketer: {
        title: "Performance Marketer(SEO, SEA, CRO",
        description: "This is a remote/hybrid position. Currently we are forming the core growth team and looking for Performance Marketers (SEO, SEA, CRO).We're open for intern and trainee Performance Marketers.",
        trial: "First of all, we will jointly look at how we can set up a win-win situation to become a permanent member of our team. Then we start with a trial period of 1 to 6 months.",
        technologies: [
            "Frontend: React (Native)",
            "Backend: Node.js",
            "Client platforms: iOS, Android, Web",
            "Datastores: DynamoDB",
            "Monitoring: CloudWatch",
            "Infra/cloud: AWS, Cloud Agnostic",
            "Version control: Github",
            "Tools: Slack, Asana, Stripe, Jira, Confluence",
        ],
        requirements: [
            "ML, AI, Python, BI",
            "Quality assurance",
            "Auto/ Manual testing",
            "Devops, Cloud mgmt",
            "Infrastr. automation",
            "Continuous integration & deployment",
            "Cyber security testing",
        ],
        offer: [
            "Fee for trial/intern period. After that a fee possible €XXXX and/or stocks depending on your skills and experience",
            "Knowledge, tools, community and training to be healthy, safe and future-proof all year round;",
            "An important role within a team of experienced digital thinkers and doers;",
            "A company that helps individuals, organizations and stakeholders grow their business through digital growth expertise;",
            "Fun and informal team members with our team and plenty of development opportunities!",
        ],
        whatweask: [
            "Pre if you have university working and thinking level;",
            "Pre if you have 1 - 5+ Years experience as a performance marketer",
            "Excellent communication skills",
            "As a performance marketer, you will be working closely with the growth team to create valuable performance. ",
            "Ability to put forth complex performance topics in a simpler form.",
            "Strong attention to detail & impeccable grasp of the English language.",
            "Excellent verbal and written communication skills.",
            "Basic knowledge on SEO, SEA & CRO.",
            "Good logical thinking and problem-solving skills",
            "A good team player",
            "You are very interested in everything related to the domain;",
            "You are meticulous, loyal, energetic, intelligent, diligent and a problem solver!",
        ],
        apply: "Are you the perfect candidate for this position and do you meet the requirements? Then apply and we will contact you as soon as possible!",
        extrainfo: [
            "Education: All levels/ University",
            "Place: Haarlem - The Netherlands, Hybrid or Remote",
            "Working hours per week: 10 - 40+",
            "Employment: Internship, Traineeship, Freelance & Contract...",
            "Responsible for: In consultation.",
        ],
    },
    Marketing_Automation_CRM: {
        title: "Marketing Automation/CRM",
        description: "This is a remote/hybrid position. Currently we are forming the core growth team and looking for Marketing Automation & CRM specialisten.We're open for intern and trainee Marketing Automation & CRM specialisten.",
        trial: "First of all, we will jointly look at how we can set up a win-win situation to become a permanent member of our team. Then we start with a trial period of 1 to 6 months.",
        technologies: [
            "Frontend: React (Native)",
            "Backend: Node.js",
            "Client platforms: iOS, Android, Web",
            "Datastores: DynamoDB",
            "Monitoring: CloudWatch",
            "Infra/cloud: AWS, Cloud Agnostic",
            "Version control: Github",
            "Tools: Slack, Asana, Stripe, Jira, Confluence",
        ],
        requirements: [
            "ML, AI, Python, BI",
            "Quality assurance",
            "Auto/ Manual testing",
            "Devops, Cloud mgmt",
            "Infrastr. automation",
            "Continuous integration & deployment",
            "Cyber security testing",
        ],
        offer: [
            "Fee for trial/intern period. After that a fee possible €XXXX and/or stocks depending on your skills and experience",
            "Knowledge, tools, community and training to be healthy, safe and future-proof all year round;",
            "An important role within a team of experienced digital thinkers and doers;",
            "A company that helps individuals, organizations and stakeholders grow their business through digital growth expertise;",
            "Fun and informal team members with our team and plenty of development opportunities!",
        ],
        whatweask: [
            "Pre if you have university working and thinking level;",
            "Pre if you have 1 - 5+ Years experience as a Marketing Automation & CRM specialisten",
            "Excellent communication skills",
            "As a Marketing Automation & CRM specialist, you’ll be working closely with the growth team to create valuable automations. ",
            "Ability to put forth complex Marketing Automation topics in a simpler form.",
            "Strong attention to detail & impeccable grasp of the English language.",
            "Excellent verbal and written communication skills.",
            "Good logical thinking and problem-solving skills",
            "A good team player",
            "You are very interested in everything related to the domain;",
            "You are meticulous, loyal, energetic, intelligent, diligent and a problem solver!",
        ],
        apply: "Are you the perfect candidate for this position and do you meet the requirements? Then apply and we will contact you as soon as possible!",
        extrainfo: [
            "Education: All levels/ University",
            "Place: Haarlem - The Netherlands, Hybrid or Remote",
            "Working hours per week: 10 - 40+",
            "Employment: Internship, Traineeship, Freelance & Contract...",
            "Responsible for: In consultation.",
        ],
    },
    Finance_IT: {
        title: "Finance - IT",
        description: "This is a remote/hybrid position. Currently we are forming the finance team and looking for a Finance - IT specialist. We're open for intern and trainee Finance - IT specialist.",
        trial: "First of all, we will jointly look at how we can set up a win-win situation to become a permanent member of our team. Then we start with a trial period of 1 to 6 months.",
        technologies: [],
        requirements: [],
        offer: [
            "Fee for trial/intern period. After that a fee possible €XXXX and/or stocks depending on your skills and experience",
            "Knowledge, tools, community and training to be healthy, safe and future-proof all year round;",
            "An important role within a team of experienced digital thinkers and doers;",
            "A company that helps individuals, organizations and stakeholders grow their business through digital growth expertise;",
            "Fun and informal team members with our team and plenty of development opportunities!",
        ],
        whatweask: [
            "Pre if you have university working and thinking level;",
            "Pre if you have 1 - 5+ Years experience in Finance and IT",
            "Excellent communication skills",
            "As a finance - IT specialist, you’ll be working closely with all the stakeholders. ",
            "Ability to put forth complex finance - IT topics in a simpler form.",
            "Strong attention to detail & impeccable grasp of the English language.",
            "Excellent verbal and written communication skills.",
            "Good logical thinking and problem-solving skills",
            "A good team player",
            "You are very interested in everything related to the domain;",
            "You are meticulous, loyal, energetic, intelligent, diligent and a problem solver!",
        ],
        apply: "Are you the perfect candidate for this position and do you meet the requirements? Then apply and we will contact you as soon as possible!",
        extrainfo: [
            "Education: All levels/ University",
            "Place: Haarlem - The Netherlands, Hybrid or Remote",
            "Working hours per week: 10 - 40+",
            "Employment: Internship, Traineeship, Freelance & Contract...",
            "Responsible for: In consultation.",
        ],
    },
    legal_It: {
        title: "Legal IT",
        description: "This is a remote/hybrid position. Currently we are forming the core legal team and looking for a Legal - IT specialist. We're open for intern and trainee Legal - IT specialist.",
        trial: "First of all, we will jointly look at how we can set up a win-win situation to become a permanent member of our team. Then we start with a trial period of 1 to 6 months.",
        technologies: [],
        requirements: [],
        offer: [
            "Fee for trial/intern period. After that a fee possible €XXXX and/or stocks depending on your skills and experience",
            "Knowledge, tools, community and training to be healthy, safe and future-proof all year round;",
            "An important role within a team of experienced digital thinkers and doers;",
            "A company that helps individuals, organizations and stakeholders grow their business through digital growth expertise;",
            "Fun and informal team members with our team and plenty of development opportunities!",
        ],
        whatweask: [
            "Pre if you have university working and thinking level;",
            "Pre if you have 1 - 5+ Years experience in Finance and IT",
            "Excellent communication skills",
            "As a finance - IT specialist, you’ll be working closely with all the stakeholders. ",
            "Ability to put forth complex finance - IT topics in a simpler form.",
            "Strong attention to detail & impeccable grasp of the English language.",
            "Excellent verbal and written communication skills.",
            "Good logical thinking and problem-solving skills",
            "A good team player",
            "You are very interested in everything related to the domain;",
            "You are meticulous, loyal, energetic, intelligent, diligent and a problem solver!",
        ],
        apply: "Are you the perfect candidate for this position and do you meet the requirements? Then apply and we will contact you as soon as possible!",
        extrainfo: [
            "Education: All levels/ University",
            "Place: Haarlem - The Netherlands, Hybrid or Remote",
            "Working hours per week: 10 - 40+",
            "Employment: Internship, Traineeship, Freelance & Contract...",
            "Responsible for: In consultation.",
        ],
    },

};


export default jobsDescription;
