interface JobDetails {
    title: string;
    description: string;
    trial: string;
    technologies: string[];  // Changed to array of strings
    requirements: string[];
    offer: string[];
    whatweask: string[];
    apply: string;
    extrainfo: string[];
}

const jobsDescription: Record<string, JobDetails> = {
    "HR_IT_Recruiter": {
        title: "HR - IT Recruiter",
        description: "This is a remote/hybrid position.  Currently we are forming the people team and looking for HR - IT Recruiters. We're open for intern and trainee HR - IT Recruiters.",
        trial: "First of all, we will jointly look at how we can set up a win-win situation to become a permanent member of our team. Then we start with a trial period of 1 to 6 months.",
        technologies: [
            "Frontend: React (Native)",
            "Backend: Node.js",
            "Client platforms: iOS, Android, Web",
            "Datastores: DynamoDB",
            "Monitoring: CloudWatch",
            "Infra/cloud: AWS, Cloud Agnostic",
            "Version control: Github",
            "Tools: Slack, Asana, Stripe, Jira, Confluence",
        ],
        requirements: [
            "ML, AI, Python, BI",
            "Quality assurance",
            "Auto/ Manual testing",
            "Devops, Cloud mgmt",
            "Infrastr. automation",
            "Continuous integration & deployment",
            "Cyber security testing",
        ],
        offer: [
            "Fee for trial/intern period. After that a fee possible €XXXX and/or stocks depending on your skills and experience",
            "Knowledge, tools, community and training to be healthy, safe and future-proof all year round;",
            "An important role within a team of experienced digital thinkers and doers;",
            "A company that helps individuals, organizations and stakeholders grow their business through digital growth expertise;",
            "Fun and informal team members with our team and plenty of development opportunities!",
        ],
        whatweask: [
            "Pre if you have university working and thinking level;",
            "Pre if you have 1 - 5+ Years experience as a HR - IT recruiter",
            "Excellent communication skills",
            "Good knowledge in IT Recruitment",
            "Sourcing the right candidates through Job portals, Advertisements, Headhunting, Networking & Employee referrals, etc.",
            "To be good at analytics and proficient in hiring through various channels, job portals, free job posting sites, social networking sites, etc.",
            "Understanding the requirements for sourcing, screening profiles, and shortlisting the candidates for a preliminary interview.",
            "Develop successful sourcing strategies to reach out to passive and active job seekers.",
            "Build good rapport with candidates throughout the interview process to ensure a positive experience.",
            "Regularly update the internal database with new resumes and bring in more innovative recruiting techniques.",
            "Good logical thinking and problem-solving skills",
            "You are very interested in everything related to the domain;",
            "You are meticulous, loyal, energetic, intelligent, diligent and a problem solver!",
        ],
        apply: "Are you the perfect candidate for this position and do you meet the requirements? Then apply and we will contact you as soon as possible!",
        extrainfo: [
            "Education: All levels/ University",
            "Place: Haarlem - The Netherlands, Hybrid or Remote",
            "Working hours per week: 10 - 40+",
            "Employment: Internship, Traineeship, Freelance & Contract...",
            "Responsible for: In consultation.",
        ],
    },
    Software_Engineer: {
        title: "Software Engineer (Javascript, AWS, Fullstack)",
        description: "This is a remote/hybrid position. Currently we are forming the core development team and looking for javascript software engineers (fullstack). We're open for intern and trainee software engineers.",
        trial: "First of all, we will jointly look at how we can set up a win-win situation to become a permanent member of our team. Then we start with a trial period of 1 to 6 months.",
        technologies: [
            "Frontend: React (Native)",
            "Backend: Node.js",
            "Client platforms: iOS, Android, Web",
            "Datastores: DynamoDB",
            "Monitoring: CloudWatch",
            "Infra/cloud: AWS, Cloud Agnostic",
            "Version control: Github",
            "Tools:  Slack, Asana, Stripe",
        ],
        requirements: [
            "ML, AI, Python, BI",
            "Quality assurance",
            "Auto/ Manual testing",
            "Devops, Cloud mgmt",
            "Infrastr. automation",
            "Continuous integration & deployment",
            "Cyber security testing",
        ],
        offer: [
            "Fee for trial/intern period. After that a fee possible €XXXX and/or stocks depending on your skills and experience",
            "Knowledge, tools, community and training to be healthy, safe and future-proof all year round;",
            "An important role within a team of experienced digital thinkers and doers;",
            "A company that helps individuals, organizations and stakeholders grow their business through digital growth expertise;",
            "Fun and informal team members with our team and plenty of development opportunities!",
        ],
        whatweask: [
            "Pre if you have university working and thinking level;",
            "Pre if you have 0.5 - 5+ Years experience as a HR - IT recruiter",
            "Good understanding of structured and unstructured databases (MySQL and DynamoDB)",
            "Knowledge of isomorphic React is an added advantage",
            "Experience in implementing well-known React workflows",
            "Experience with Javascript backend framework like node.js",
            "Ability to learn new technologies and languages quickly",
            "Good time-management skills",
            "Experience with Restful API services",
            "Delivering a complete front end application",
            "Professional, precise communication skills",
            "Deep knowledge of Angular/Node.js/React practices and commonly used modules based on extensive work experience",
            "Good knowledge in Javascript and able to handle Array & Objects built-in methods",
            "Good logical thinking and problem-solving skills",
            "A good team player",
            "You are very interested in everything related to the domain;",
            "You are meticulous, loyal, energetic, intelligent, diligent and a problem solver!",
        ],
        apply: "Are you the perfect candidate for this position and do you meet the requirements? Then apply and we will contact you as soon as possible!",
        extrainfo: [
            "Education: All levels/ University",
            "Place: Haarlem - The Netherlands, Hybrid or Remote",
            "Working hours per week: 10 - 40+",
            "Employment: Internship, Traineeship, Freelance & Contract...",
            "Responsible for: In consultation.",
        ]
    },
    Software_Tester: {
        title: "Software Tester",
        description: "This is a remote/hybrid position. Currently we are forming the core development team and looking for software testers. We're open for intern and trainee software testers.",
        trial: "First of all, we will jointly look at how we can set up a win-win situation to become a permanent member of our team. Then we start with a trial period of 1 to 6 months.",
        technologies: [
            "Frontend: React (Native)",
            "Backend: Node.js",
            "Client platforms: iOS, Android, Web",
            "Datastores: DynamoDB",
            "Monitoring: CloudWatch",
            "Infra/cloud: AWS, Cloud Agnostic",
            "Version control: Github",
            "Tools: Slack, Asana, Stripe, Jira, Confluence",
        ],
        requirements: [
            "ML, AI, Python, BI",
            "Quality assurance",
            "Auto/ Manual testing",
            "Devops, Cloud mgmt",
            "Infrastr. automation",
            "Continuous integration & deployment",
            "Cyber security testing",
        ],
        offer: [
            "Fee for trial/intern period. After that a fee possible €XXXX and/or stocks depending on your skills and experience",
            "Knowledge, tools, community and training to be healthy, safe and future-proof all year round;",
            "An important role within a team of experienced digital thinkers and doers;",
            "A company that helps individuals, organizations and stakeholders grow their business through digital growth expertise;",
            "Fun and informal team members with our team and plenty of development opportunities!",
        ],
        whatweask: [
            "Pre if you have university working and thinking level;",
            "Pre if you have 0,5 - 5+ Years experience as a HR - IT recruiter",
            "Good knowledge in manual testing",
            "Good knowledge in test case preparation",
            "Good written and verbal communication skills",
            "Strong analytical and documentation skills to present findings to team members",
            "Analyze requirements for validity and feasibility",
            "Execute all levels of testing",
            "Detect, track defects and inconsistencies",
            "Good logical thinking and problem-solving skills",
            "A good team player",
            "You are very interested in everything related to the domain;",
            "You are meticulous, loyal, energetic, intelligent, diligent and a problem solver!",
        ],
        apply: "Are you the perfect candidate for this position and do you meet the requirements? Then apply and we will contact you as soon as possible!",
        extrainfo: [
            "Education: All levels/ University",
            "Place: Haarlem - The Netherlands, Hybrid or Remote",
            "Working hours per week: 10 - 40+",
            "Employment: Internship, Traineeship, Freelance & Contract...",
            "Responsible for: In consultation.",
        ],
    },
    Business_Analyst: {
        title: "Business Analyst",
        description: "This is a remote/hybrid position. Currently we are forming the core development team and looking for business analysts.We're open for intern and trainee business analysts.",
        trial: "First of all, we will jointly look at how we can set up a win-win situation to become a permanent member of our team. Then we start with a trial period of 1 to 6 months.",
        technologies: [
            "Frontend: React (Native)",
            "Backend: Node.js",
            "Client platforms: iOS, Android, Web",
            "Datastores: DynamoDB",
            "Monitoring: CloudWatch",
            "Infra/cloud: AWS, Cloud Agnostic",
            "Version control: Github",
            "Tools: Slack, Asana, Stripe, Jira, Confluence",
        ],
        requirements: [
            "ML, AI, Python, BI",
            "Quality assurance",
            "Auto/ Manual testing",
            "Devops, Cloud mgmt",
            "Infrastr. automation",
            "Continuous integration & deployment",
            "Cyber security testing",
        ],
        offer: [
            "Fee for trial/intern period. After that a fee possible €XXXX and/or stocks depending on your skills and experience",
            "Knowledge, tools, community and training to be healthy, safe and future-proof all year round;",
            "An important role within a team of experienced digital thinkers and doers;",
            "A company that helps individuals, organizations and stakeholders grow their business through digital growth expertise;",
            "Fun and informal team members with our team and plenty of development opportunities!",
        ],
        whatweask: [],
        apply: "Are you the perfect candidate for this position and do you meet the requirements? Then apply and we will contact you as soon as possible!",
        extrainfo: [
            "Education: All levels/ University",
            "Place: Haarlem - The Netherlands, Hybrid or Remote",
            "Working hours per week: 10 - 40+",
            "Employment: Internship, Traineeship, Freelance & Contract...",
            "Responsible for: In consultation.",
        ],
    },
    IOS_Android_Dev: {
        title: "IOS/Android Developer",
        description: "",
        trial: "",
        technologies: [],
        requirements: [],
        offer: [],
        whatweask: [],
        apply: "",
        extrainfo: []
    },
    UX_UI_Designer: {
        title: "UX/UI Designer",
        description: "",
        trial: "",
        technologies: [],
        requirements: [],
        offer: [],
        whatweask: [],
        apply: "",
        extrainfo: []
    },
    DevOps_Engineer: {
        title: "DevOps Engineer",
        description: "",
        trial: "",
        technologies: [],
        requirements: [],
        offer: [],
        whatweask: [],
        apply: "",
        extrainfo: []
    },
    Product_Owner: {
        title: "Product Owner",
        description: "",
        trial: "",
        technologies: [],
        requirements: [],
        offer: [],
        whatweask: [],
        apply: "",
        extrainfo: []
    },
    Cyber_Security_Engineer: {
        title: "Cyber Security Engineer",
        description: "",
        trial: "",
        technologies: [],
        requirements: [],
        offer: [],
        whatweask: [],
        apply: "",
        extrainfo: []
    },
    AI_Data_Engineer: {
        title: "AI Data Engineer",
        description: "",
        trial: "",
        technologies: [],
        requirements: [],
        offer: [],
        whatweask: [],
        apply: "",
        extrainfo: []
    },
    Growth_Hacker: {
        title: "Growth Hacker",
        description: "",
        trial: "",
        technologies: [],
        requirements: [],
        offer: [],
        whatweask: [],
        apply: "",
        extrainfo: []
    },
    AI_Data_Marketing_Analyst: {
        title: "AI Data Marketing Analyst",
        description: "",
        trial: "",
        technologies: [],
        requirements: [],
        offer: [],
        whatweask: [],
        apply: "",
        extrainfo: []
    },
    Performance_Marketer: {
        title: "Performance Marketer(SEO, SEA, CRO",
        description: "",
        trial: "",
        technologies: [],
        requirements: [],
        offer: [],
        whatweask: [],
        apply: "",
        extrainfo: []
    },
    Marketing_Automation_CRM: {
        title: "Marketing Automation/CRM",
        description: "",
        trial: "",
        technologies: [],
        requirements: [],
        offer: [],
        whatweask: [],
        apply: "",
        extrainfo: []
    },
    Finance_IT: {
        title: "Finance - IT",
        description: "",
        trial: "",
        technologies: [],
        requirements: [],
        offer: [],
        whatweask: [],
        apply: "",
        extrainfo: []
    },

};


export default jobsDescription;
