name: Cypress Tests

on: 
  push:
    branches:
      - 'automated-test'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      # Install NPM dependencies, cache them correctly
      - name: Install dependencies
        run: |
          cd Mostprosapp
          npm ci --verbose

      # Start Expo Web server
      - name: Start Expo Web
        run: |
          cd Mostprosapp
          expo start --web

      # Wait for Expo Web server to be ready
      - name: Wait for Expo Web
        run: |
          timeout 300 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:19006)" != "200" ]]; do sleep 5; done'

      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: Mostprosapp
          start: npx cypress run