name: Cypress Tests

on: 
  push:
    branches:
      - '*'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: |
          cd web
          npm ci --verbose

      - name: Build project
        run: |
          cd web
          npm run build

      - name: Start application
        run: |
          cd web
          npx vite --host &
        env:
          CYPRESS_BASE_URL: http://localhost:3000
      
      - name: Wait for server to be ready
        run: sleep 15

      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          working-directory: web
          runTests: true
