name: Cypress Tests

on: 
  push:
    branches:
      - 'abdel_test_branch'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  # Install NPM dependencies, cache them correctly

      - name: Install dependencies
        run: |
          cd web
          npm ci --verbose

      # Install Cypress

      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          working-directory: web
          runTests: false

      # and run all Cypress tests
      
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: web
          build: npm run build
          start: npx vite --host
          